### ISSUE TITLE
JsonApiSerializer should hoist all includes into top-level "linked" object

### ISSUE THREAD

**Issue by pvormittag** [thephpleague/fractal#104]
Based on my understanding of the current JSON API spec and [fetching includes](http://jsonapi.org/format/#fetching-includes); Given a primary resource `a` with includes of `b` and `b.c`, I need to return a response from the request `/a?include=b,b.c` as:

```json
{
  "a": [
    {
      "id": "1",
      "links": {
        "b": "1",
      }
    }
  ],
  "linked": {
    "b": [
      {
        "id": "1",
        "links": {
          "c": "1"
        }
      }
    ],
    "c": [
      {
        "id": "1"
      }
    ]
  }
}
```

Using Fractal with JsonApiSerializer, I would expect to be able to create my Transformers as:

```php
class ATransformer
{
  protected $availableIncludes = [
    'b'
  ];

  public function transform($a)
  {
    return [
      'id' => $a->id,
      'links' => [
        'b' => $a->b->id,
      ]
    ]; 
  }

  public function includeB($a)
  {
    return $this->item($a->b, new BTransformer, 'b');
  }
}

class BTransformer
{
  protected $availableIncludes = [
    'c'
  ];

  public function transform($b)
  {
    return [
      'id' => $b->id,
      'links' => [
        'c' => $b->c->id,
      ]
    ];
  }

  public function includeC($b)
  {
    return $this->item($b->c, new CTransformer, 'c');
  }
}

class CTransformer
{
  public function transform($c)
  {
    return [
      'id' => $c->id,
    ];
  }
}
```
... Then to put it altogether, I simply need to:

```php
$fractal = new Fractal\Manager();
$collection = new Collection($a_models, new ATransformer, 'a');

$fractal->parseIncludes('b,b.c');
echo $fractal->createData($collection)->toJson();
```

However, doing it this way returns the below response, which seems incorrect. Notice the `c` resources are included as `linked.linked.c` instead of `linked.c`.

```json
{
  "a": [
    {
      "id": "1",
      "links": {
        "b": "1",
      }
    }
  ],
  "linked": {
    "b": [
      {
        "id": "1",
        "links": {
          "c": "1"
        }
      }
    ],
    "linked": {
      "c": [
        {
          "id": "1"
        }
      ]
    }
  }
}
```

**Comment by vinkla** [comment]
Any update on this? Would be great to have it in. 

@philsturgeon What does the future bring for Fractal? Will this package be fully compatible with http://jsonapi.org/ standards in the future?

**Comment by philsturgeon** [comment]
That is the plan but I’m having to consider a bit of a re-write to get there. 

For now if JSON-API is your thing you’ll either need to consider an alternative solution or get stuck in with some PRs. :)

-- 
Phil

**Comment by vinkla** [comment]
@philsturgeon Aah okay, thanks for letting me know :) 

JSON-API version 1.0 seems to be released in just two days.

**Comment by philsturgeon** [comment]
Thank f**k they’ll stop changing it all around and we can focus on proper support.

**Comment by vinkla** [comment]
Haha :)

**Comment by jasonlewis** [comment]
JSON API has since been overhauled.
