### ISSUE TITLE
belongsToMany relationship cannot be included

### ISSUE THREAD

**Issue by JonoB** [thephpleague/fractal#108]
I'm getting an error with a belongsToMany, and we want to include that relationship for a collection via a transformer. I've ignored the lazy vs eager loading issue for now; everything is just lazy loaded.

> Argument 1 passed to Fs\Transformers\CategoryTransformer::transform() must be an instance of Fs\Category, instance of Illuminate\Database\Eloquent\Collection given, called in /var/www/filmsupply.dev/vendor/league/fractal/src/Scope.php on line 263 and defined

Looks like it _may_ something to do with the data is being transformed to an array with a `data` array key  (DataArraySerializer). 

``` php
// ClipTransformer
public function transform(Clip $clip)
{
    return [
        'id' => (int)$clip->id,
        'name' => $clip->name,
    ];
}

public function includeCategories(Clip $clip)
{
    $categories = $clip->categories;

    return $this->item($categories, new CategoryTransformer);
}
```

``` php
//CategoryTransformer
public function transform(Category $category)
{
    return [
        'id' => (int)$category->id,
        'name' => $category->name,
    ];
}
```

**Comment by Batalha** [comment]
Engraçado já o meu funcionou com item.... se eu colocar o colletion, dá esse mesmo erro do colega assima....
return $this->item($categories, new CategoryTransformer);
