### ISSUE TITLE
Return a null resource?

### ISSUE THREAD

**Issue by troygilbert** [thephpleague/fractal#124]
I've got a resource with a custom transformer. It has some available includes for other resources with custom transformers. Sometimes, those other resources are null. If that child resource is included, I get an error that you can't transform a null value (due to type hinting as in the examples). I can fix that by providing a null default value to the `transform()` method, and my `transform()` method can return null, but I then get an exception thrown on an attempted `array_merge()` call where Fractal tries to merge the return value with another array. How can I avoid this? What's the correct way for me to indicate a child resource is not present (null)?

**Comment by newtonianb** [comment]
Hi @philsturgeon , we actually have a scenario where we need this behavior. We have the api interacting with backbone relational (essentially eloquent orm for backbone). 

So when we want to clear a relation in the front end we would want to return null for that relation so that the front end backbone relations can auto update (backbone relational takes care of injection data in your relations automatically). Right now since returning null in fractal returns nothing what ends up happening is the data in backbone relation is not cleared, kind of a bummer we have to resort to hacks in the front end.

Any advice how to get this null or some kind of false value return working in fractal?

**Comment by rickshawhobo** [comment]
I would also be interested in returning a null as an option when the node doesn't not exist. Maybe I will do that PR as you suggested.

**Comment by alexglue** [comment]
@troygilbert @rickshawhobo @philsturgeon The simple way to fix your trouble is to use something like this:

```
	public function includeAdditional(MainObject $object)
	{
                //MainObject has nullable property additional:
		return $object->additional ? $this->item($object->additional, new AdditionalTransformer(), 'dictionary') : $this->null();
	}

**Comment by marsd** [comment]
@alexglue I am trying your method in here but I am getting a DataArraySerializer exception null() not :

```php
public function includeManagedBy(Company $company)
{
    return $company->managed_by ? $this->item($company->managed_by, new AgencyTransformer, 'managed_by') : $this->null();
}
```

```php
Fatal error: Call to undefined method League\Fractal\Serializer\DataArraySerializer::null() in \wnmp\html\api\src\vendor\league\fractal\src\Scope.php on line 318
```

**Comment by alexglue** [comment]
@marsd i guess this is because of different version of fractal. I'm using "league/fractal": "dev-master", that contains much more JSON-API-compatible code.

**Comment by marsd** [comment]
I've just updated to dev-master, same error message. Looking in the current Serializable sources, there is indeed a null() in JsonApiSerializer, but not in the other serializers.

Is simply returning a null value appropriate for now?

**Comment by digitlimit** [comment]
I have pulled off all my hairs because of this same issue.

     Argument 1 passed to App\Transformers\BookTransformer::transform() must be an instance of      App\Models\State, null given, called in   /media/sf_www/verimarked.dev/vendor/league/fractal/src/Scope.php on line 338 and defined

In Laravel when a record does not exist in a table doing something like this:
    Book::find(2); //returns null if not found and this when passed to transformer asthmatically throws the exception above

Please whats the way forward, should I just return  a `null` like suggested here.

I found this in  `League\Fractal\TransfomerAbstract`

    protected function null()
    {
        return new NullResource();
    }

But this  exception is being thrown when I tried using it:
Call to undefined method League\Fractal\Serializer\DataArraySerializer::null()

**Comment by alexglue** [comment]
@digitlimit God, you free to use any serializer you want. Just extend it from DataArraySerializer and add implementation of null() you mentioned. You could set your custom serializer in some kind of FractalManager or FractalSerive consists of your framework where you would like to use fractal.

**Comment by alexglue** [comment]
@digitlimit 
Example of use in Yii framework:

```
/**
 * Class FractalManager
 * Dummy class to integrate Fractal\Manager to Yii as component with no fatal
 */
class FractalManager extends League\Fractal\Manager
{
	const INCLUDES_PARAM_NAME = 'include';

	public $enableLinking = false;
	public $baseUri;

	public function init()
	{
		$this->baseUri = $this->baseUri? : Yii::app()->getBaseUrl(true);
		$this->setSerializer(new EmbedSerializer($this->enableLinking? $this->baseUri : null));

		$includes = Yii::app()->request->getParam(self::INCLUDES_PARAM_NAME);
		if ($includes)
		{
			$this->parseIncludes($includes);
		}
	}
}


/**
 * Class EmbedSerializer
 */
class EmbedSerializer extends DataArraySerializer
{
    public function null()
    {
        return new NullResource();
    }
}

**Comment by digitlimit** [comment]
@alexglue thanks a million times. You just saved my head from going bald.

**Comment by digitlimit** [comment]
@alexglue after creating my own custom serializer then I can do this 

     return new NullResource();

right?

**Comment by alexglue** [comment]
@digitlimit yes, you could. NullResource is just another simple class like this:

```
/*
 * This file is part of the League\Fractal package.
 *
 * (c) Phil Sturgeon <me@philsturgeon.uk>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace League\Fractal\Resource;

/**
 * Null Resource
 *
 * The Null Resource represents a resource that doesn't exist. This can be
 * useful to indicate that a certain relationship is null in some output
 * formats (e.g. JSON API), which require even a relationship that is null at
 * the moment to be listed.
 */
class NullResource extends ResourceAbstract
{
    /**
     * Get the data.
     *
     * @return mixed
     */
    public function getData()
    {
        // Null has no data associated with it.
    }
}

**Comment by digitlimit** [comment]
@alexbilbie never mind, works like never before

I simply added this in to custom serializer 

      public function null()
      {
              return ['data' => null];
      }

and works!!!

      .....
      "state": {
        "data": 
      }

**Comment by kmuenkel** [comment]
Returning null will omit the field entirely.  If you want it to be there, but show an empty array, try this:
    public function includeSomething(Model $model)
    {
        return $model->something ? $this->item($model->something, app($yourTransformer)) : $this->item(null, function () {return [];});
    }

You could also set up a base-class that overrides $this->null to return that.

**Comment by bradbird1990** [comment]
@kmuenkel this does not work unfortunately, the error that comes back is...

```
Invalid return value from League\Fractal\TransformerAbstract::includeSomething(). Expected League\Fractal\Resource\ResourceInterface, received array.
```

**Comment by bradbird1990** [comment]
@kmuenkel worked like a charm, I tried returning null by itself and got the below error but returning an item with an empty array does the job.

```
Invalid return value from League\Fractal\TransformerAbstract::includeHomeContactDetails(). Expected League\Fractal\Resource\ResourceInterface, received array.
```

**Comment by cmeza** [comment]
(necro I know . . . but . . . I still ended up here)

I tried various combinations of the offered solutions, but this is what worked for me.

    class PrimaryTransformer 
    {
        . . .
    
        public function includeSomething(Model $model)
        {
            return $this->collection($model->something, new SomethingTransformer());
        }
    }
    
    
    class SomethingTransformer
    {
        public function transform(Something $something = null) // also added `= null` 
        {
            if (!something) return []; // this is what finally worked for me
            
            return [
                // transform here
            ];
        }
    }

**Comment by mojtaba-gheytasi** [comment]
In main MainTransformer:
    public function includeRelation(Entity $entity)
    {
        $relation = $entity->getRelation();

        if ($relation === null) {
            return $this->null();
        }

        return $this->item($relation , new RelationTransformer);
    }
--------------------
Then you should customize ArraySerializer:

    use League\Fractal\Serializer\ArraySerializer;

    class **CustomArraySerializer** extends ArraySerializer
    {
        public function null()
        {
            return null;
        }
    }

--------------------
Finally in controller(or anywhere):

        $resource = new Item($entity, new MainTransformer);
        $this->fractal = new Fractal;
        $this->fractal->setSerializer(new **CustomArraySerializer**);
        $responseData = $this->fractal->createData($resource)->toArray();


And in response we see the following result:
{
    "id": 1,
    "name": "Alex",
    "relation": null
}
