### ISSUE TITLE
JsonApiSerializer wraps items in an array. Why?

### ISSUE THREAD

**Issue by mrkrstphr** [thephpleague/fractal#125]
The [JSON API spec says](http://jsonapi.org/format/#document-structure-individual-resource-representations) that an individual item *SHOULD* be represented as a single object. It looks like fractal is returning in wrapped in array. 

Was this a conscious decision? And if so, what are the thoughts about making it configurable? I'd be happy to submit a PR either way.

**Comment by philsturgeon** [comment]
Making JSON-API work properly will be part of the v1.0 rewrite. 

I'm clearing up old JSON-API related issues to make way for one simple issue on the topic now @jasonlewis and @willishq are in charge.
