### ISSUE TITLE
Set the defaultIncludes dynamically

### ISSUE THREAD

**Issue by MartijnThomas** [thephpleague/fractal#143]
I was wondering if there is a way to set the defaultIncludes dynamically in a Transformer.

What I want to do is, if the user is the owner of a resource I want (by default) to include a related resource. Is this possible?

**Comment by chrismichaels84** [comment]
If you can put together some code of what you would *like* to see, I'd bet we can crank out a PR pretty quickly. What do you envision?

**Comment by jasonlewis** [comment]
You could probably to something similar in the constructor of your transformer to dynamically set the default includes.
