### ISSUE TITLE
[Laravel-5.0] Compatibility with latest version of Laravel

### ISSUE THREAD

**Issue by jaoued** [thephpleague/fractal#150]
Hi,

I noticed this package are not yet compatible with Laravel 5 (like transformer for example).

Any news about future updates ?

Thanks.

**Comment by brayniverse** [comment]
Hey @jaoued, what doesn't work in Laravel 5 for you? As far as I am aware Fractal is a framework agnostic package and should work in most scenarios. Even though Fractal is a separate project from Laravel I'm sure if you can produce a PR which fixes any problems you're facing they will integrate it with this package. If you're unable to put a PR together, listing the problems in more detail here may encourage others to help out with the PR :)

**Comment by GrahamCampbell** [comment]
@brayniverse I assume @jaoued is referring to the illuminate paginator. Fractal only supports Laravel 4's paginator, and not laravel 5's.

**Comment by brayniverse** [comment]
Thanks for filling in the blanks for me @GrahamCampbell. Laravel 5 should be at a stable release this month so hopefully you will see a new paginator implementation soon @jaoued.

**Comment by jaoued** [comment]
@brayniverse Sorry, i forgot to respond. Yes it's a problem with paginator @GrahamCampbell .

**Comment by maximebeaudoin** [comment]
@GrahamCampbell @philsturgeon  I' wondering if we should create a new Adapater for Laravel 5 or just update the current to support Laravel 5. Because if we want to keep Laravel 4.* support for next fractal version, we should propably create a new one.

**Comment by philsturgeon** [comment]
Yep, two adapters. Fun times.

**Comment by jaoued** [comment]
Hi, any news about how to use collection transformer with L5 ?

**Comment by etiennemarais** [comment]
+1 Currently all dependencies are unstable while we wait for this to be tagged. Please can you tag a stable release.

**Comment by philsturgeon** [comment]
Done! Sorry for the delay there. 

-- 
Phil
