### ISSUE TITLE
JSON-API-style deep relationships not possible

### ISSUE THREAD

**Issue by thomasvanlankveld** [thephpleague/fractal#151]
According to the JSON-API spec, it should be possible to [request deep relationships using a dot notation](http://jsonapi.org/format/#fetching-includes):

```
GET /posts/1?include=comments.author
```

This results in Fractal trying to call

```
includeComments.author()
```

Which is not possible in PHP. I can make the comment authors available by declaring it as `$availableIncludes = ['comments.author' => 'commentsAuthor']` but this does not adhere to the JSON-API spec.

I'm not sure how deep I'd have to delve into Fractal to get this working, because adding this to `TransformerAbstract` after 175: 

```php
        // Check if the method name actually exists
        if (!method_exists($this, $methodName)) {
            return false;
        }
```

Removes the error but then simply ignores the `author` part of the inclusion.

**Comment by philsturgeon** [comment]
You do not need to define grand-child includes in a transformer.

PostTransformer would have `protected $availableIncludes = ['comments'];` and CommentsTransformer would have `protected $availableIncludes = ['author'];`

Nice and easy!

**Comment by thomasvanlankveld** [comment]
Ah cool!

Had to switch to ArraySerializer to see this in action, it's an absolute horror to get this to work for the sideloading Serializers.

**Comment by philsturgeon** [comment]
Yeah sideloading is fundamentally broken until I get to rewrite it all JSON-API is not what this was designed for. 

-- 
Phil
