### ISSUE TITLE
Strange behaviour when including a model in a transformer using laravel

### ISSUE THREAD

**Issue by Ortix92** [thephpleague/fractal#152]
I have 2 transformers: `EpisodeTransformer` and `ShowTransformer`. A show `hasMany` episodes.

In my `EpisodeTransformer` I have the following method to include the show into the response:

```
    public function includeShow(Episode $episode)
    {
        $show = $episode->show;

        return $this->item($show, new ShowTransformer);
    }
```

However laravel throws the following exception:

`call_user_func() expects parameter 1 to be a valid callback, class 'Animekyun\Transformers\ShowTransformer' does not have a method 'includeShow'`

So I just put in an empty method in my `ShowTransformer`:

```
    public function includeShow()
    {
    }
```

Note that I do have a `transform()` method in my `ShowTransformer` class.

And then everything works. I don't think this is how it should work? What is going on? Why do I need to include that method? It's not even mentioned in the docs.

**Comment by jasonlewis** [comment]
You shouldn't need to unless you're defining the available includes on both of the transformers.
