### ISSUE TITLE
$this->fractal->createData($resource)->toArray() fails

### ISSUE THREAD

**Issue by sangar82** [thephpleague/fractal#163]
Hi Phil!
I'm trying to update my app to L5. I updated to the last version (dev-master) to get the latests changes with the new  PaginatorAdapter, but when try to do ->toArray from createData, I get the following error:

````php
FatalErrorException in Grammar.php line 144:
Maximum function nesting level of '100' reached, aborting!
````

this is the method I use to Paginate and the $rootScope var has content:

````php
    protected function respondWithPaginator( $paginator, $transformer)
    {
        // append the querystring to the pagination links
        $queryStrings = array_except( Input::query(), 'page' );
        $paginator->appends($queryStrings);

        $resource = $paginator->getCollection();

        $resource = new Collection($resource, $transformer);
        $resource->setPaginator(new IlluminatePaginatorAdapter($paginator));
 
        $rootScope = $this->fractal->createData($resource);
 
        return $this->respondWithArray($rootScope->toArray());
    }  
````

Thanks!

**Comment by sangar82** [comment]
If I do a call with POSTMAN it's working OK, but if I do a call inside my website, $rootScope->toArray() fails.

Is a problem of mine, not of Fractal, but I haven' discovered yet the cause of this error.

**Comment by sangar82** [comment]
I've noticed that the problem is when I use includes, if there aren't the calls inside my website are OK....
POSTMAN is always OK

**Comment by philsturgeon** [comment]
This is pretty vague, I’m sorry! Can you do a little debugging?

-- 
Phil

**Comment by sangar82** [comment]
Hi Phil!

Apologies for this description so vague, but I don't understand what is  happening. I´m migrating my L4 app to L5. 

I have and API that is consumed by mobile aplications and the web frontend. When I do calls to the API from outside the web (POSTMAN, mobiles apps) there are not problems, but when i do a call from the website, I get a FatalErrorException with the nesting level.

I think that is a problem with my API Calls inside the website (to work properly in L4 I solved this with: http://blog.antoine-augusti.fr/2014/04/laravel-calling-your-api/). You need to hack the request params for set the request with the Api request vars. 

I noticed too, the error occurs when include relations, I have compared the two objects in L4 and L5 and have the same content, the paginator have the items, but the nesting lever error occurs when try to convert the include results to array. If there aren't includes, works fine.

````php
$rootScope = $this->fractal->createData($resource);
return $this->respondWithArray($rootScope->toArray());
````
At this moments, I can solve this adding this line  on top of my ApiController, but I don't know if this solution is suitable...
````php
ini_set('xdebug.max_nesting_level', 200);
````

**Comment by AMRoche** [comment]
I've ran in to this issue today and managed to find out that it's to do with having circular dependencies in transformers; i.e.;

Two Models; Model A and Model B.
A's Transformer has B as a default include, and B's Transformer has A as a default include.

This seems to replicate the issue. I would have thought that the `setRecursionLimit` method would handle this case though? Will update after further research.

**Comment by philsturgeon** [comment]
That should only be the case if Model A and Model B both reference each other, but yeah if you have defaultIncludes on A -> B and B -> A then its embed forever.

So, my suggestion would be to not do that. Make them optional, then infinite recursions are impossible, you can just have "lots" instead.

Or lower the recursion level yeah :)

**Comment by AMRoche** [comment]
@philsturgeon The recursion limit was set to ten, and yet it was still recursing way past that to the point of hitting the function call limit. Seems like the recursion limit isn't quite triggering?

I've made all the parameters optional now though using the parseIncludes; hopefully has sorted it!

**Comment by philsturgeon** [comment]
It could be that self referencing items don’t quite notice. I’ll take a look into that.

-- 
Phil

**Comment by AMRoche** [comment]
Cool, want me to file a 'formal' issue?

**Comment by philsturgeon** [comment]
Yessir

-- 
Phil
