### ISSUE TITLE
setRecursionLimit() function does not seem to be limiting circular dependencies

### ISSUE THREAD

**Issue by AMRoche** [thephpleague/fractal#168]
Issue being created off the back of comments in issue [163](https://github.com/thephpleague/fractal/issues/163).

Expected behaviour;
I would expect the `setRecursionLimit` function to limit the depth to which these are circularly included.

Actual behaviour;
PHP Error of 'maximum nested function depth reached', even when the recursion limit is set to 1.

Ways to reproduce;

```
Two Models; Model A and Model B.
A's Transformer has B as a default include, and B's Transformer has A as a default include.
```

Call the `$this->fractal->createData($resource)->toArray()` methods.

**Comment by jasonlewis** [comment]
The intended use of the recursion limit is to prevent things like `foo.bar.baz.bing.bang.boom`. So it would cut it off at say, `foo.bar.baz`.

Granted. Your circular dependency is actual recursion. I think this needs to be looked at and we probably need to rename some things so it makes a bit more sense.

**Comment by willishq** [comment]
What specific use-case do you have for requiring circular dependency?

**Comment by ryanmortier** [comment]
@willishq I just ran into this issue today and here is my use case:

My database structure is as follows:
Three tables, `accounts`, `contracts`, and `prices`
Each `account` has many `contracts`
Each `contract` belongs to one `account`
Each `contract` can have many `prices`
Each `price` belongs to one `contract`
Therefore, each `account` has many `prices` through `contracts`

I start out by querying my database for all `prices` belonging to an `account`.

I then send this collection to a `PriceTransformer` and inside that transformer it has a default includes of `contracts` that use a `ContractTransformer` and inside that transformer it has a default includes of `prices`.

That's exactly where I want it to stop though.

I want a collection of all `prices > contract < prices`

You can see how it's a circular reference and will continue looping. The way I've solved this for now is sending the default included prices on the `ContractTransformer` to a different `Prices2Transformer` that doesn't have the default includes for the `contract`.

Is there a better way of doing this?

**Comment by andrewmclagan** [comment]
Same situation, my use case:

`organsiations` have many `users`

`users` have an `organisation`

Thus we have a recursion loop in the transformers. Seems like a common use case?
