### ISSUE TITLE
[Feature Request] Empty Includes

### ISSUE THREAD

**Issue by texmorgan** [thephpleague/fractal#169]
I'd like to be able to get an empty set of embedded data.

{
  "id" : 4,
  "address" : 
   {
     "street" : "123 Main",
     "city" : "Chicago",
     "state" : "IL",
     "zip" : "12354",
   }
}

This will allow for consistent data structures.

So a similar record without an address will look like:

{
  "id" : 4,
  "address" : 
   {
   }
}

**Comment by willishq** [comment]
I think this is more a case for a custom serializer than core functionality.
