### ISSUE TITLE
Wiki Should Be Disabled?

### ISSUE THREAD

**Issue by GrahamCampbell** [thephpleague/fractal#171]

**Comment by fireproofsocks** [comment]
I'm not sure if the wiki should be disabled, or actually *used*: the docs on the league page are disappointingly sparse.  E.g. it's not clear how to modify the basic output structure.  One consistent failure of the current docs is that there are not enough juxtapositions between the resource/transformer output with the final JSON/Array output.  

Likewise, the conventions used in passing URL parameters to affect behaviors is not explained in enough depth to avoid serious fiddling.

If the wiki were enabled, users could help contribute examples and refinements to the docs.

**Comment by GrahamCampbell** [comment]
The wiki is unused and is open to public writing. No point in it atm. Should be disabled.

**Comment by philsturgeon** [comment]
@fireproofsocks users can already send pull requests to the docs, as I would welcome you to do so with your feedback. 

I rarely fine that wikis open to public writing are of any value, they're usually a mess. Disabling.
