### ISSUE TITLE
semantic versioning (realease 1.0 already)

### ISSUE THREAD

**Issue by clphillips** [thephpleague/fractal#173]
So [you say](https://github.com/thephpleague/fractal/blob/master/CONTRIBUTING.md) you use [semver](http://semver.org), but you don't.

> Randomly breaking public APIs is not an option.

That's the definition of being in 1.0.

By having a release < 1.0 you're saying **DO NOT USE IN PRODUCTION, API IS NOT FINALIZED**.

Is that really what you intend? If not, publish 1.0 so I can start using it already! Damn thing as been out for forever.

**Comment by Kevinrob** [comment]
:+1: I vote for it too

**Comment by Art4** [comment]
[One goal](https://github.com/thephpleague/fractal#goals) of this project is: "Work with standards like HAL and JSON-API but also allow custom serialization"

See also this comment: https://github.com/thephpleague/fractal/issues/104#issuecomment-63351585

So, please help e.g. in #187 to reach v1.0

**Comment by philsturgeon** [comment]
v1.0 is in the works. The new owners @jasonlewis and @willishq will make a roadmap and some milestones for this soon I expect. Keep an eye out for that.
