### ISSUE TITLE
ResourceInterface inconsistency

### ISSUE THREAD

**Issue by stefanmajoor** [thephpleague/fractal#174]
In the ResourceInterface the setData()/constructor method will accept any mixed data, while the getdata() method returns an array of ArrayIterator.

In the ResourceAbstract implementation however, it can be seen that the given data is returned one on one to the getData. That means that getData only returns an array/ArrayIterator if the given data was an array/Iterator. There is no check if the data object is an array/ArrayIterator. This therefore does not satisfy the contract.

**Comment by philsturgeon** [comment]
I guess this is just a case of docblocks being outdated. Instead of `mixed` it should probably say `array|ArrayIterator`. 

Have you had any actual problems here? Any errors? Or did you just notice this inconsistency looking at code?

**Comment by stefanmajoor** [comment]
I noticed it when I went through the code indeed. Since there was no type checking going on, and was not familiar with the code I was not completely sure what was going on

**Comment by philsturgeon** [comment]
Seems like you’re on top of this. 

Can you either fire over a docblock fix, a code fix or a test to show a problem?

**Comment by stefanmajoor** [comment]
I will do both a docblock fix and a code fix
