### ISSUE TITLE
XML Support

### ISSUE THREAD

**Issue by harikant** [thephpleague/fractal#178]
I have used Fractal to create an awesome json api.  Now one of my clients wants XML output.

So I can create XSD files and generate XML using DOMDocument, but is this possible using a custom Fractal serializer?  

If I return an XML element from the collection or item classes how will it construct the final output?

This way I can take advantage of the sorting/filtering/includes that I have built into my base Transformer classes.

**Comment by philsturgeon** [comment]
You can take the toArray method and wrap it in some general XML conversion, absolutely.

**Comment by judos** [comment]
Can you explain a bit closer how this works? I just looked at this but I don't understand how exactly you meant this. thx!

**Comment by philsturgeon** [comment]
A 5 year old issue isn't the best place to get support. Please make a new issue, or try to contact one of the maintainers of this project.
