### ISSUE TITLE
Why does pagination return a full next url but cursor does not?

### ISSUE THREAD

**Issue by benswinburne** [thephpleague/fractal#179]
When using cursors, a key `"next": "MTA="` for example is returned, meaning that the client/consumer has to compile the next URL itself.

```
"meta": {
    "cursor": {
        "current": 0,
        "prev": "MA==",
        "next": "MTA=",
        "count": 10
    }
}
```

The obvious downside here is that the query string parameter required to send must be guessed or looked up in documentation. In the examples provided `cursor` and `prevCursor` are used. I've used `?next=x` before for easy guessing.

When using pagination, a `links` key is output containing for example

```
"meta": {
    "pagination": {
        "total": 100,
        "count": 10,
        "per_page": 10,
        "current_page": 1,
        "total_pages": 10,
        "links": {
            "next": "http://api.local/users/?page=2"
        }
    }
}
```

I was wondering if this was a intentionally different behaviour of it it might be worth implementing a links array for cursors?

**Comment by philsturgeon** [comment]
Yeah, that cursor example is a bit complex. See if you can add links with next and previous links to simplify things.

**Comment by benswinburne** [comment]
You mean implement it and create a PR or just update my example to demonstrate what I'm suggesting as opposed to what Fractal does currently?

**Comment by philsturgeon** [comment]
Both. The example would change along with the PR to change fractals behavior: adding the links.

-- 
Phil

**Comment by ahjorth** [comment]
Any updates on this?

**Comment by matthewtrask** [comment]
there hasn't been any updates on this in a few years so I will close this for now. If it is still an issue please feel free to reopen.
