### ISSUE TITLE
Scope toArray doesn't preserve numeric keys

### ISSUE THREAD

**Issue by luoshiben** [thephpleague/fractal#180]
I have a scenario where my custom serializer returns an item in the format [numeric id] => [key1 => val1, key2 => val2]. Usually the numeric id is the primary key of the entity being returned. The problem is that when toArray() is called on the Scope object returned to Manager@createData, numeric keys aren't preserved. The Scope@toArray method creates an array of metadata, then merges the serialized data with the metadata using array_merge, which resets numeric indices. (Scope.php line 226) Is there a reason that it array_merge has to be used, or could that line be replaced with `return $data + $meta` so that numeric keys are preserved? Thanks for any help.

**Comment by philsturgeon** [comment]
Don’t try and use numeric keys? 

Whats the JSON you’re trying to output?

**Comment by luoshiben** [comment]
@philsturgeon Thanks for the response. In my specific scenario I use a single transformer (per model/resource) to prepare data for output to both a REST API and also a Firebase repository. My custom serializer sets the passed in `$resourceKey` as the key and the transformed data array as the value of the Item. For output to Firebase I pass in the primary key of the relational database record as the resourceKey to the serializer, then POST/PUT the array to Firebase. This way I can easily reference the entity or node by id. For API output I set the resourceKey as the name of the model being transformed. The transformed data is in array form when its sent to the Firebase API and converted to JSON when its returned by my REST API. The JSON standard wouldn't support a numeric property key, of course, so it would have to be quoted if being converted to JSON, but this isn't a problem when I'm using it as an array.

In the end, it would be cool if any resourceKey passed to a serializer was preserved, whether that's string or number. At the moment I'm using a locally-forked version of Fractal with the change I suggested and so far things seem to be working ok. However, there are likely other considerations or potential issues that I'm not aware of that could make this problematic. I defer to your expertise here!

**Comment by willishq** [comment]
I don't think that numeric keys should be preserved, you shouldn't be relying on data to be returned in a specific order and if you need to order by a specific thing, when you consume the API you should ideally be sorting the data there.

**Comment by luoshiben** [comment]
Hey @willishq, in my use case preserving numeric keys actually has nothing to do with order. The numeric indices have intrinsic significance like a string-based key does. Specifically and for example, resourceKey 3273 represents the database id, or primary key, of the resource or entity who's data is being transformed. Because this key has significance, it needs to be preserved.

The problem arises from the use of array_merge in Scope@toArray() when merging meta data with resource data. By definition, the array_merge function resets numeric keys.
> Values in the input array with numeric keys will be renumbered with incrementing keys starting from zero in the result array.

Two solutions come to mind:

1. Force the indice to string format by concatenating a random token to the resourceKey, like '-' + 3273. Before sending the transformed data in a response or to Firebase (in my case), I'd first need to run a filter on the transformed data to remove the '-' token from any index that it had been appended to. Ugh.

2. Use array addition instead of array merge in the Scope@toArray() method. Doing this solves the problem with numeric indices very simply. However, unintended consequences could arise depending on the structure of the $meta data. To illustrate:

 With array_merge:
 > If the input arrays have the same string keys, then the later value for that key will overwrite the previous one. If, however, the arrays contain numeric keys, the later value will not overwrite the original value, but will be appended. Values in the input array with numeric keys will be renumbered with incrementing keys starting from zero in the result array.

 With array addition:
 > The + operator returns the right-hand array appended to the left-hand array; for keys that exist in both arrays, the elements from the left-hand array will be used, and the matching elements from the right-hand array will be ignored.

 This means that while array addition will preserve numeric keys, it may ignore some meta data if the programmer sets a numeric indice on the resource that is also being used in the $meta data.

3. Instead of using array_merge or array addition in the Scope@toArray() method, merge the $data and $meta arrays in a manner that follows the rules of array_merge to protect $meta data, but still preserves numeric keys. For example:

 ```php
 function array_merge_preserve_numeric_keys()
 {
     $array = array();
     $arguments = func_get_args();
     $argNum = 0;
     foreach($arguments as $arg) {
         $argNum++;
         if(!is_array($arg)) {
             trigger_error("Argument $argNum is not an array", E_USER_WARNING);
             return;
         }
         foreach($arg as $key => $value) {
             if(array_key_exists($key, $array) && is_numeric($key)) {
                 $array[] = $value;
             } else {
                 $array[$key] = $value;
             }
         }
     }
     return $array;
 }
 ```

**Comment by philsturgeon** [comment]
Put the key in the object?

--
Phil Sturgeon

**Comment by luoshiben** [comment]
For a normal API response that is exactly what I do. The key is stored in the object and the resourceKey is actually set as the name of the entity type being returned by the endpoint. However, I also use  Fractal for transforming the resource for pushing to Firebase, which is a cloud-based NoSQL datastore and eventing engine. In that case, I need to publish the resource or entity being transformed as a new node on the JSON datastore. The key for that node must be the ID of the entity from an associated relational database so that it can be accessed again. Yes, I could have used guids instead of ints or structured the NoSQL data differently, but for my requirements using the relational db ID works well, and hopefully wouldn't need to be changed based on the transformation layer.

I know that a ton of work is being done on Fractal right now -- thanks to all of those who are contributing! This is an amazing package that provides a lot of value to many developers. If modifying Fractal to support preservation of numeric indices makes sense for the project as a whole then I'd love to help in this small area if I can. Otherwise, "it is what it is" and I'll find some other way to deal with my requirements, even if not as pretty. Thanks as always.
