### ISSUE TITLE
Transforming array inside the original resource

### ISSUE THREAD

**Issue by lasselehtinen** [thephpleague/fractal#182]
Hi,

I hope I can explain this right. I am building a REST API based on an industry standard which has a very deep nesting. It's a Laravel app with Model1->hasMany('Model2')->hasmany('Model3') kind of structure. This is the simplest example I could find:

```php
array:9 [
  "id" => 2
  "created_at" => "2015-05-19 10:56:39"
  "updated_at" => "2015-05-19 10:56:39"
  "product_id" => 12901
  "title_type_id" => 2
  "value" => "01"
  "description" => "Distinctive title (book); Cover title (serial); Title on item (serial content item or reviewed resource)"
  "notes" => "The full text of the distinctive title of the item, without abbreviation or abridgement. For books, where the title alone is not distinctive, elements may be taken from a set or series title and part number etc to create a distinctive title. Where the item is an omnibus edition containing two or more works by the same author, and there is no separate combined title, a distinctive title may be constructed by concatenating the individual titles, with suitable punctuation, as in “Pride and prejudice / Sense and sensibility / Northanger Abbey”."
  "title_elements" => array:2 [
    0 => array:5 [
      "title_detail_id" => 2
      "title_text" => "Macbeth"
      "subtitle" => null
      "value" => "01"
      "description" => "Product"
    ]
    1 => array:5 [
      "title_detail_id" => 2
      "title_text" => "Shakespeare"
      "subtitle" => null
      "value" => "02"
      "description" => "Collection level"
    ]
  ]
]
```
I can control the top level just fine. But is there any way I could transform the array inside? In this case it is the title_elements, which comes out as is.

```php
return [
    'value'             => $title_detail->value,
    'description'       => $title_detail->description,
    'title_elements'    => $title_detail->title_elements
];
```
Is this even possible or what should be the correct way to handle these deep nesting arrays so that I could still control the output with Fractal?

**Comment by deefour** [comment]
`'title_elements'` should me moved to the list of default includes on the title detail transformer. You can then specify a new collection of your title_elements to be transformed by fractal. [Learn more about default includes here](http://fractal.thephpleague.com/transformers/#default-includes).

**Comment by lasselehtinen** [comment]
I knew about default includes before, but it did not came to my mind that I could use them for the nested structure. It actually makes sense now when I think of it. Dunno would this be worth mentioning in the documentation? But anyway thanks a lot, now I have nice looking nested output.
