### ISSUE TITLE
Prevent URL slash from being escaped in the response

### ISSUE THREAD

**Issue by newtonianb** [thephpleague/fractal#185]
I'm returning a URL from one of my transformers and it's being encoded in the respect

```
{
   "url": "http\/\/:example\/...."
}
```

How can I prevent this in my transformer? I tried to place this url under the key "links" as I saw some examples but same thing happens.

```
"links" => {
  "uri" => ''http\/\/:example\/....'
}
```

**Comment by opengeek** [comment]
This is the default behavior of PHP's `json_encode()` function. You have to pass `JSON_UNESCAPED_SLASHES` (in PHP 5.4+) to the function to prevent this.

**Comment by newtonianb** [comment]
Thanks!
