### ISSUE TITLE
Includes when not using Eloquent.

### ISSUE THREAD

**Issue by bweston92** [thephpleague/fractal#189]
I've just started using plain models, using my repository fetch and build instances. However if my model has say 10 available includes that aren't on the model. They would require a repository being in the transformer to load the appropriate model of the include.

Eloquent made this easy by obviously using the relationships of the model.

### My options
- Inject all required repositories in the constructor.
- I could inject the Illuminate container to the transformer but this is coupling the transformers with Illuminate.
- Make my own container interface that allows me to build classes?
- Have base transformers and then extend the transformers with specific implementations for each framework.

How do others handle this?

**Comment by brayniverse** [comment]
Could you inject the related repository into your model and access them via public methods?

```php
// article.php model
...
public function comments()
{
    return $this->commentsRepository->findByArticleId($this->id);
}
...
// usage
$article->comments();
```

**Comment by bweston92** [comment]
I don't think adding the repositories to my model sounds a good idea.



—

**Comment by brayniverse** [comment]
It's one option, what are your arguments against it?

**Comment by bweston92** [comment]
I don't believe my models should be aware of that logic, maybe just me. I don't think I've ever seen it either.




 I'm determined to have a container contract and have framework specific implementations.



—

**Comment by brayniverse** [comment]
I support your desire to separate logic from framework constraints but you should be careful about over engineering. If you can imagine yourself needing to switch to another framework in the future then it could be worth the effort now.

How would this container function? Am I correct to assume you are want something you can inject it into the transformer which resolves any repository, kind of like this:

```php
class RepositoryContainer
{
    public function commentsRepository(){...}
    public function articlesRepository(){...}
}

class ArticleTransformer extends TransformerAbstract
{
    /**
     * @var RepositoryContainer
     */
    protected $repositoryContainer;

    public function __construct(RepositoryContainer $repositoryContainer) {...}

    public function includeComments(Article $article)
    {
        $comments = $this->repositoryContainer->commentsRepository->getByArticleId($article->id);

        return $this->collection($comments, new CommentTransformer);
    }
}
```

This would reduce your injected dependencies in the transformer but it's only disguising what dependencies your transformer needs. Of course you can look at the code and see `$this->repositoryContainer->commentsRepository->...` but in my opinion there aren't any _real_ benefits to this approach other than tidying your `__construct` method.

As I said that's my *opinion* and I'm working on the assumption that you're planning on doing it that way, what are your comments on this?

**Comment by deefour** [comment]
I'd like to help, but am confused by your phrasing and lack of code describing what you're trying to accomplish or avoid. I get lost on your first sentence

> I've just started using plain models, using my repository fetch and build instances.

**Comment by bweston92** [comment]
Right then, here is an example where it is easy.
```
<?php

class Product extends Eloquent
{
  /** @return \Illuminate\Database\Eloquent\Relations\BelongsToMany */
  public function category();
}
```

The corresponding transformer would look similar to this:

```
<?php

class ProductTransformer
{
  protected $availableIncludes = ['categories'];
  public function transform(Product $model);
  public function includeCategories(Product $model)
  {
    return $this->collection($model->categories, new CategoryTransformer);
  }
}
```

See that is easy but the following is a bit harder.

```
<?php

class Product
{
  /** @return string */
  public function categoryId();
}
```

Transformer options

Inject the repositories.
```
<?php

class ProductTransformer
{
  protected $availableIncludes = ['categories'];
  public function __construct(CategoryRepository $categoryRepository);
  public function transform(Product $model);
  public function includeCategories(Product $model)
  {
    $categories = $this->categoryRepository->getByProduct($product->key());
    return $this->collection($categories, new CategoryTransformer);
  }
}
```

Use a container
```
<?php

class ProductTransformer
{
  protected $availableIncludes = ['categories'];
  public function __construct(Container $container);
  public function transform(Product $model);
  public function includeCategories(Product $model)
  {
    $categoryRepository = $this->container->make(CategoryRepository::class);
    $categories = $categoryRepository->getByProduct($product->key());
    return $this->collection($categories, new CategoryTransformer);
  }
}
```

**Comment by brayniverse** [comment]
Is that Laravel's Container or your own Container class?

**Comment by bweston92** [comment]
@brayniverse Actually I will make my own contract that will be implemented by the infrastructure, so a IlluminateContainer will be injected into the constructor in this case.

**Comment by jasonlewis** [comment]
You could look at making a repository factory that has the job of returning the proper repository. Essentially a container. Which it sounds like you're doing anyway.
