### ISSUE TITLE
Symfony \ Component \ Debug \ Exception \ FatalErrorException Can't inherit abstract function League\Fractal\Pagination\PaginatorInterface::count() (previously declared abstract in Countable)

### ISSUE THREAD

**Issue by jdwit** [thephpleague/fractal#19]
When using the Paginator on a Fractal collection, I get the following eror:

Symfony \ Component \ Debug \ Exception \ FatalErrorException
Can't inherit abstract function League\Fractal\Pagination\PaginatorInterface::count() (previously declared abstract in Countable)

On my server I run PHP 5.3.3. On my local machine I run PHP 5.4.21, no problem there. Commenting out line 24 in League/Fractal/Pagination/PaginatorInterface.php;

```
public function count();
```

prevents the error.

**Comment by vigneshmuthukrishnan** [comment]
Hi friends i have some problems 
for laravel  Pagination

FatalErrorException in C:\xampp\htdocs\new_laravel\vendor\laravel\framework\src\Illuminate\Foundation\ProviderRepository.php line 146:
Cannot instantiate interface Illuminate\Contracts\Pagination\Paginator

**Comment by bencorlett** [comment]
Looks like you're having issues with dependency injection within your Laravel environment and out of the scope of this package

Sent from my iPhone

Please excuse my brevity

**Comment by vigneshmuthukrishnan** [comment]
Thank you for information  @bencorlett  and I clear my issues.
 composer update and change my controller code
