### ISSUE TITLE
How can I eager load included when they have parameters

### ISSUE THREAD

**Issue by kfirba** [thephpleague/fractal#190]
Hello.

I'm using fractal to build some API. I love the way is simplifies the process. 
Since there are many relations which I can load with the API, I would love to use eager loading so I won't query my DB way too many times. For that, I need to parse the `included` parameter.

However, what happens when the `include` has some parameters? maybe something like:
```
api.example.com/v1/posts?include=comments:take(10):order(created_at|desc)
```

Currently I have a `ApiController`:

```
    /**
     * @param Request $request
     */
    public function __construct(Request $request)
    {
        $this->request = $request;

        if ($request->has('include')) {
            $this->fractal()->parseIncludes($request->get('include'));
        }

        $this->registerMiddlewares();
    }
```

Now it will tell fractal to load the wanted relationships, however, I can't just go ahead and include the relationship anywhere else in my app since I have to parse the `include` parameter now and apply any constraint that the user passed. 

How can I eager load that? As it stands, the Manager class will parse the `include` parameter and give me an access to the parsed `include` only when I'm **including** the relationship which means it's too late to eager load the relationship.

Any idea?

**Comment by fenos** [comment]
Yhea i had the same doubt too, if someone had some experience with it will be helpful

**Comment by brayniverse** [comment]
I was thinking about this myself. It may be helpful if there was a way to parse the query to see what arguments have been passed. `$parser->getIncludes('books')->getModifier('take') // 10`. If we can discuss an API I'd be happy to prepare a PR for this functionality.

**Comment by brayniverse** [comment]
Looks like this functionality already exists in the Manager class. You can eager load the relations by calling `getRequestedIncludes()` and with `getIncludeParams('paramName')` you can figure out whether you need to limit or order your queries.

**Comment by kfirba** [comment]
@brayniverse how would you use that? We need to eager load the relation before we are trying to respond with a collection or an item. I guess it means that somewhere in the controller/repository we need to do it. 

Any example?

**Comment by brayniverse** [comment]
Yes you'd need to find a way to pass it to however you're collecting the data for your response. I'm out for the day today but once I'm back I'd be happy to write an example.

**Comment by brayniverse** [comment]
```php
class PostsController
{
    protected $fractal;
    protected $postsRepository;

    public function __construct(Manager $manager, PostsRepository $postsRepository)
    {
        $this->fractal = $manager;
        $this->postsRepository = $postsRepository;
    }

    public function getAll(Request $request)
    {
        $includes = $this->fractal->getRequestedIncludes();

        if (in_array('comments', $includes)) {
            $params = $this->fractal->getIncludeParams('comments');
            $limit = isset($params['take']) ? $params['take'] : 10;
            $order = isset($params['order']) ? $params['order'] : 'created_at';

            $posts = $this->postRepository
                ->withComments($limit, $order)
                ->all();
        } else {
            $posts = $this->postRepository->all();
        }

        return response()->json($posts);
    }
}
```

**Comment by brayniverse** [comment]
I don't know how you are retrieving data from your database so the example below only demonstrates how to use the Manager class to retrieve the include parameters (and set default values). The example presumes you're using [Eloquent](https://github.com/illuminate/database) for interacting with the database, this could be adapted to whatever your requirements are.

```php
class PostsController
{
    public function index()
    {
        $posts = Post::all();
    
        if (in_array('comments', $this->fractal->getRequestedIncludes())) {
            $commentParams = $this->fractal->getIncludeParams('comments');

            $commentLimit = isset($commentParams['take']) ? $commentParams['take'][0] : 10;
            $commentOrderCol = 'created_at';
            $commentOrderDir = 'asc';
    
            if (isset($commentParams['order'])) {
                $commentOrderCol = $commentParams['order'][0];
                $commentOrderDir = isset($commentParams['order'][1]) ? $commentParams['order'][1] : $commentOrderDir;
            }
    
            $posts->load(['comments' => function($query) use ($commentLimit, $commentOrderCol, $commentOrderDir) {
                $query
                    ->limit($commentLimit)
                    ->orderBy($commentOrderCol, $commentOrderDir);
            }]);
        }
    
        $resource = new \League\Fractal\Resource\Collection($posts, new PostTransformer);
    
        return $this->fractal->createData($resource)->toJson();
    }
}
```

`$commentParams['take']` will return an array of values found between the parenthesis and split by the delimiter, `|`. This is why I'm using `$commentParams['take'][0]` to get the value and it is why we can get the order and direction to sort the results in. Some validation should be done here because somebody could accidentally do `sort(asc|created_at)` and you'll be trying to do this `orderBy('asc', 'created_at')`.

Let me know if any of the above doesn't make sense. I'm going to try and prepare a PR to the documentation to help others understand how to interact with the include parameters, any questions from you will help me know what to write.

**Comment by kfirba** [comment]
@brayniverse thanks. I will go through this later on today.

**Comment by brayniverse** [comment]
:+1: Hopefully it helps you.

**Comment by fenos** [comment]
@brayniverse Very useful, thank you very much!!
