### ISSUE TITLE
How could I not have Data for the include

### ISSUE THREAD

**Issue by rogeryu23** [thephpleague/fractal#193]
I have a product transformer and manager is using DataArraySerializer by default
but i hope for the include, e.g. i don't want to have data: key for skus for product.
How could I achieve it, since I thought only one serializer is defined for fractal manager

Product:
{
    "data": {
        "id": 2,
        "name": "Cloth",
        "description": "The awesome cloth for men",
        "price": 50,
        "skus": {
            "data": [
                {
                    "id": 4,
                    "spec": "S",
                    "quantity": 10
                },
                {
                    "id": 5,
                    "spec": "L",
                    "quantity": 5
                },
                {
                    "id": 6,
                    "spec": "M",
                    "quantity": 60
                }
            ]
        }
    }
}

**Comment by szkuwa** [comment]
Had the same problem here; problem (or feature?) was in the default ArraySerializer

```php
    public function collection($resourceKey, array $data)
    {
        return array($resourceKey ?: 'data' => $data);
    }
```

I just made custom serializer that extends the default ArraySerializer and overrides this function to
```php
return $data;
```
So far it works without a problem

**Comment by rogeryu23** [comment]
i thought default is DataArraySerializer not ArraySerailizer

**Comment by szkuwa** [comment]
Yes, you are correct the default is DataArraySerializer;
Don't know why I did put that "default" word there

**Comment by willishq** [comment]
Sorry for the late response. The `'data'` field is there by default as a way of standardising the API response. As @szkuwa stated you can override the `ArraySerializer` and create your own implementation for whatever format you wish to use.

**Comment by jonwhittlestone** [comment]
Please could you include code for the overriding class here as a guide :))) thanks @willishq / @szkuwa

**Comment by philsturgeon** [comment]
It needs to be there or you'll never be able to add meta data, pagination, links, etc. Please, it's not a big deal, and if it is you can make your own serializer which is crippled and only does half of the functionality.
