### ISSUE TITLE
Exclude attributes

### ISSUE THREAD

**Issue by avilchinsky** [thephpleague/fractal#194]
Often case is then it returns a model via factory and model has a lot of atributes.
We don't know which model we will get. So the collection initialising will transform to many switch blocks.
More convinient is to define a list of excluded fields for this.

**Comment by philsturgeon** [comment]
You can do anything you like in the serializer.

```
$data = $model->toArray();
unset($data['foo']);
return $data;
```

I prefer whitelist to blacklist, as excluding lets new fields slip in accidentally.
