### ISSUE TITLE
Ability to return arrays from includes

### ISSUE THREAD

**Issue by leon13** [thephpleague/fractal#196]
It occurred to me today that it'd be handy to be able to return an array from an include, rather than explicitly `ResourceAbstract`.

Reasoning:
I have a model `Booking`, which has a transformer, returning essential data. If I needed some extra data returned, it'd be handy to be able to use something like `includeExtraData`, which simply returns an array of the extra data.

Does this sound sensible? Should this data always go in meta? or am I missing something completely? Either way, awesome package!

**Comment by jasonlewis** [comment]
Depends what the data is but it sounds like it belongs to meta.

**Comment by catalinux** [comment]
@leon13  the content if includeExtraData si actual data (like embeded data) or info about data (like pagination)?

For example JSOANPI format has a new key besides data and meta, named included. For example, your response might look like this:

```json
{
   "data":[

   ],
   "includeded":[

   ],
   "meta":{
      "pagination":{

      }
   }
}

**Comment by willishq** [comment]
I agree with @jasonlewis in that this belongs in Meta.
