### ISSUE TITLE
0.13 plan?

### ISSUE THREAD

**Issue by appkr** [thephpleague/fractal#197]
I extracted a [Laravel/Lumen package](https://github.com/appkr/fractal) on top of this fractal to use it as a submodule of my personal project, hoping that it be also helpful to other people. The package is utilizing `setMeta()`, which is available only through 0.13@dev or dev-master. What that means is that any parent project that depends upon my package should lower the composer minimum-stability setting to dev. Which may ruin the the parent project by pulling unwanted dev packages.

So, as the title says, my question is that when are you going to tag the current code base to 0.13? I need the `setMeta()` badly. If I did misunderstand something, please correct me. Anyway, thanks for the great package.

**Comment by chrislentz** [comment]
+1

**Comment by catalinux** [comment]
`  "prefer-stable": true` would not solve your issue?

**Comment by appkr** [comment]
@catalinux Let me try your recommendation late today and update the result. Thanks.

**Comment by appkr** [comment]
@catalinux Lazy update. 

```bash
$ laravel new test-fractal && cd test-fractal
// (after adding "prefer-stable": true on the composer.json)
$ composer require "appkr/fractal:0.5.*" // appkr/fractal depends on league/fractal

Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - appkr/fractal 0.5.2 requires league/fractal 0.13.*@dev -> no matching package found.
    - appkr/fractal 0.5.1 requires league/fractal 0.13.*@dev -> no matching package found.
    - appkr/fractal 0.5.0 requires league/fractal 0.13.*@dev -> no matching package found.
    - Installation request for appkr/fractal 0.5.* -> satisfiable by appkr/fractal[0.5.0, 0.5.1, 0.5.2].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
Installation failed, reverting ./composer.json to its original content.
```

In conclusion, adding `"prefer-stable": true` on the root composer.json(^1) did not pull the `league/fractal` correctly. So tricky... Composer !!

**Comment by catalinux** [comment]
How about:
    "league/fractal": "dev-master as 0.12",

**Comment by jasonlewis** [comment]
You should be able to use `0.13.*@dev` to get the latest and greatest. We've got some plans in mind now and hopefully we can get some things updated in the coming weeks.

**Comment by appkr** [comment]
@jasonlewis I may did something wrong. The following structure made an error.

```
/
├── composer.json              // #1
└── vendor
    ├── appkr                                           
    │   └── fractal
    │       └── composer.json  // #2
    └── league
        └── fractal
            └── composer.json  // #3

// #1
{
  "require": {
    "...": "...",
    "appkr/fractal": "0.5.*"
  },
  "prefer-stable": true
}

// #2
{
  "require": {
    "...": "...",
    "league/fractal": "0.13.*@dev"
  }
}
```
