### ISSUE TITLE
JsonApiSerializer item becomes an array

### ISSUE THREAD

**Issue by christickner** [thephpleague/fractal#199]
See: https://github.com/thephpleague/fractal/blob/master/src/Serializer/JsonApiSerializer.php#L41

Why are we making the data an array here?

**Comment by philsturgeon** [comment]
It needs to be there or you'll never be able to add meta data, pagination, links, etc. Please, it's not a big deal, and if it is you can make your own serializer which is crippled and only does half of the functionality.
