### ISSUE TITLE
When is the next release date?

### ISSUE THREAD

**Issue by moon0326** [thephpleague/fractal#221]
Hi,

It looks like the last version (0.12.0) was pushed on March. When do we expect a release?

I believe there are at least a few changes in the current repository.

Thanks,
Moon

**Comment by willishq** [comment]
Hi, we are just roadmapping the next release, obviously there have been a few pull requests merged in to master since the last release which might warrant a minor release for now but we're really trying to push for a major release in the near future!

**Comment by moon0326** [comment]
Good to hear that!

Thanks!
Moon
