### ISSUE TITLE
JsonApiSerializer not working on 0.12.0

### ISSUE THREAD

**Issue by rephiscorth** [thephpleague/fractal#222]
Instructions on README and website suggest you run `composer require league/fractal` to install, but it pulls `^0.12.0`, which `JsonApiSerializer` doesn't work (or to be more accurate, the class is just 89 lines, where `master` has one with 380+ lines). I believe either master must be tagged to be pulled by composer or, if it isn't stable yet, let the docs says `JsonApiSerializer` doesn't work on 0.12.0

**Comment by burriko** [comment]
I'm really hoping there's a new release tagged soon for the same reason. The new JsonApiSerializer is such a big step up from the 0.12 one that I'm now requiring dev-master on a project, which is never ideal.

**Comment by fojuth** [comment]
+1 - also waiting for a new release.

**Comment by milesj** [comment]
+1 - Same. 

Would love other JSON API spec feature though before a tag is released, like column filtering: http://jsonapi.org/format/#fetching-sparse-fieldsets Perhaps this can be done automatically in the transformer layer somehow.

**Comment by acorncom** [comment]
Looks like there's been a new release (https://github.com/thephpleague/fractal/releases/tag/0.13.0), should this get closed?
