### ISSUE TITLE
Order of includes in JSON output.

### ISSUE THREAD

**Issue by webkenny** [thephpleague/fractal#223]
I have a transformer which uses `$defaultIncludes` to bring in other related models. That all works a treat. My question is how might I affect where the output goes in my transformer output? Consider this basic example. Assume `objects` is the included data (e.g. `$defaultIncludes = ["objects"];`)

```
{
  "data": {
    "id": "1475b9c0-ce05-4ff6-a35a-e07fe3e9b35c",
    "name": "Daffy Bunny Company",
    "links": [
      {
        "rel": "self",
        "uri": "/accounts/1475b9c0-ce05-4ff6-a35a-e07fe3e9b35c"
      }
    ],
    "objects": {
      "data": [
        {
          "id": 2,
          "name": "Primary",
        },
        {
          "id": 3,
          "name": "Secondary",
        }
      ]
    }
  }
}
```

I would like to force the `links` to be at the bottom of the JSON output. Am I being OCD or is that something I can massage Fractal into doing?

If it's helpful this is my transform method...

```
    /**
     * I can transform, I can transform ya!
     *
     * @return array
     */
    public function transform(Account $account)
    {
        return [
          'id' => $account->id,
          'name' => $account->name,
          'links' => [
            [
              'rel' => 'self',
              'uri' => '/accounts/' . $account->id,
            ]
          ],
        ];
    }
```

Is this the type of thing I might use a serializer for?

*(Full Disclosure: I asked this question on a discussion forum but, honestly, seeing that it's not anywhere in the documentation or obvious to me in the codebase, I figured asking here is more appropriate. If we come up with an answer, I'll document it there - and issue a pull request for the docs as well)*

**Comment by philsturgeon** [comment]
Order of output doesn't matter to a computer so it shouldn't matter to you. ;)

--
Phil Sturgeon

**Comment by webkenny** [comment]
This is pretty much exactly what I was hoping you'd say. OCD episode
averted. Thanks Phil. 

-- 
Kenny Silanskas
@webkenny

http://linkedin.com/in/kennysilanskas
http://about.me/webkenny

My email address is changing!
me@webkenny.com
