### ISSUE TITLE
Am I using Fractal Correctly?

### ISSUE THREAD

**Issue by dtirer** [thephpleague/fractal#225]
I'm using Fractal for a Laravel API I'm developing.  I'm finding that my endpoints are very slim (which is fine!) but that a lot of the heavy lifting is happening in my transformers.  For example, lets say your endpoint is User/Dashboard.  So you'll need to retrieve:

1) the User (User Model)
2) Profile info (Profile Model)
3) Friends (Friend Model)
4) Favorite Books (Book Model) for the sake of example.

So my endpoint might look something like:

// DashboardController

```
public function index()
{
$user = $this->userRepository->find(Authorizer::getResourceOwnerId());
return $this->respondWithItem($user, $this->userTransformer);
}
```

So that's pretty simple.  But my URL might look something like:

`user/dashboard?include=profile,friends,books`

and my Transformers will be responsible for interacting with the Models / Repositories and querying for the correct data sets (Friends, Books, Profile, and any constraints that are tied to those).

In fact, because so many of my endpoints are 'User Oriented' , most of them end up fetching the User (just like the above Controller method) and passing it off to the transformer to figure out what happens next, based on the include parameters it receives.

Is this an appropriate use of the Transformers or am I tackling this incorrectly?

**Comment by willishq** [comment]
I would suggest that you're not tackling this correctly, the transformers should only be concerned with what data gets sent to the API consumer. I would suggest creating some form of service class to handle your flow and only use the transformers to transform data to a standardised form of output.
