### ISSUE TITLE
Help needed?

### ISSUE THREAD

**Issue by pradius-fut** [thephpleague/fractal#229]
Hi,
I was wondering if there is __anything__ you need help with to get the next release and the initial implementation of json-api ready.

Patrick

**Comment by willishq** [comment]
Hi, I'm currently running checks and usability before pushing the new release (v0.13.0) at the weekend!

After this there will be a push between myself and @jasonlewis to get the project ready for v1.0.0

**Comment by pradius-fut** [comment]
That's great news, thanks.
You guys are doing great work!
