### ISSUE TITLE
Custom link URLs

### ISSUE THREAD

**Issue by milesj** [thephpleague/fractal#230]
It would be nice to be able to customize the URLs generated by the JSON API, as seen here: https://github.com/thephpleague/fractal/blob/master/src/Serializer/JsonApiSerializer.php#L72

Currently it's hard-coded based on the type and the ID. My type is usually singular, while my URLs are plural, so this is always wrong. Furthermore, this doesn't work with sub-resource style URLs.

It would be nice if it was on the `Transformer` object, like so.

```
class UserProfileTransformer extends TransformerAbstract 
{
    public function url($id) 
    {
        return "/api/users/$id/profile";
    }
}
```

**Comment by bencromwell** [comment]
That would make sense to do if JSON API was the only Serializer but it isn't. 

There's a couple of other bits and pieces that are starting to crop up now that JSON API support is being looked for more and more. 

It looks as though multiple interfaces are needed to customize this behaviour, or some additional concept in order to tie in Serializer specific behaviour without corrupting the intention of the transformers. Otherwise the transformers are going to end up containing a ton of logic specific to the use case of the JSON API serializer, which doesn't make sense when there are other serializers available. It feels like a Liskov violation. 

`interface UrlContract`? Provides two methods, one for the singular URL (api/resource/id) taking the ID param, and one for the index (api/resource)? Then any serializer, be it JSON API or your own custom serializer, can optionally do things if the transformer implements this contract? This might be a bit tricky in `fillRelationships`.

Would be interested to hear people's thoughts on this.

**Comment by milesj** [comment]
I just noticed in the docs that the links object is defined within the transformer: http://fractal.thephpleague.com/resources/

Perhaps this might be the easiest approach. Any "meta" or "links" or any JSON API related functionality can simply be defined in that way. The serializer would just have to be smart enough to not overwrite it, and defined them if they don't exist.

**Comment by ln-francesco-figari** [comment]
I think I'm currently following @milesj's idea, extending JsonApiSerializer and overriding the `item()` method. Something like this:

``` php
public function item($resourceKey, array $data)
{
    // Extract links from the resource attributes
    $custom_links = [];
    if (isset($data['jsonapi->links'])) {
        $custom_links = $data['jsonapi->links'];
        unset($data['jsonapi->links']);
    }

    // JsonApi serialization
    $resource = parent::item($resourceKey, $data);

    // Reintroduce the custom links
    if ($custom_links && $this->shouldIncludeLinks()) {
        $resource['data']['links'] += array_map(
            function($url) {
                return $this->baseUrl . '/' . $url;
            },
            $custom_links
        );
    }

    return $resource;
}
```

A cleaner approach to setting links and meta entries would be great :)

**Comment by willishq** [comment]
I'm currently in the process of rethinking the whole serializer and transformer interaction to allow more flexibility but still maintain integrity, if it ends up getting to  a point where people can just set and do whatever they want with no structure then the whole point of Fractal has been lost but I do agree that there needs to be more flexibility in certain areas which are becoming problematic, JSON-API being one of them.

**Comment by lukasoppermann** [comment]
Any news on this? I would like to use a `slug` instead of an `id` in the self links and related links.

**Comment by psicomante** [comment]
I implemented a "overrides" key in the transformer in order to overrides parts of the resource inside a extended JsonApiSerializer in a similar way @ln-francesco-figari did.

```
class FooTransformer {
   */
  public function transform(Foo $foo) {
    return
      'id'   => $foo->getId(),
      'name' => $foo->getName(),
      '_overrides' => [
        'links' => [
          'self' => '/bar/'. $foo->getBarId() .'/foo/'. $foo->getId(),
        ]
      ]
    ];
  }
}
```

inside Serializer

```
  public function item($resourceKey, array $data) {
    $resource = parent::item($resourceKey, $data);

    // overrides link['self']
    if (isset($data['_overrides'])) {
      foreach ($data['_overrides'] as $key => $override) {
        // override only existing values
        if (!isset($resource['data'][$key]))
          continue;

        $resource['data'][$key] = array_merge($resource['data'][$key], $override);
      }
      unset($resource['data']['attributes']['_overrides']);
    }

    return $resource;
  }
```

**Comment by belohlavek** [comment]
@willishq is there a solution for this yet?

**Comment by lukasoppermann** [comment]
Hey @belohlavek as far as I know @greydnls is the new leed of the project.

**Comment by belohlavek** [comment]
@lukasoppermann thanks for heads-up. Did you find a way to use a slug for links?

**Comment by lukasoppermann** [comment]
@belohlavek no I actually re-thought my idea and figured it is a bad idea. Instead of using a different url and breaking json-api standards I am just using filters now, so if you want to get something by slug you just do: `/endpoint/?filter[slug]=slug-of-item`.

**Comment by a-komarev** [comment]
Still no solution on it? In my system types are singular and urls are plural what JSON API allows. There is no way to achieve this with Fractal right now.

**Comment by hongaar** [comment]
I'm just running into the same problem. Should we open a new issue or can this issue be re-opened?
 (cc @willishq @greydnls)
