### ISSUE TITLE
Including some params on collections in Laravel 5

### ISSUE THREAD

**Issue by jbardnz** [thephpleague/fractal#240]
Hey

So I am using Fractal in my Laravel 5.1.1 project. I have an include on my Listing transformer like so:

    public function includeSecondaryImages(Listing $listing)
    {
    	$listingImages = $listing->images;
    
    	//filter only secondary images
    	$listingImages = $listingImages->filter(function($listingImage){
    		return !$listingImage->isMain();
    	});
    
    	return $this->collection($listingImages, new ListingImageTransformer);
    }

This works fine if I am returning a Listing as an item. But when I return some Listings as a collection I get the following error: 

    Call to undefined method Illuminate\Database\Query\Builder::SecondaryImages()

View full error here: http://i.imgur.com/Tt8oQdP.png

It seems Laravel is looking for a relationship called SecondaryImages when one doesn't exist?

**Comment by willishq** [comment]
I would suggest that somewhere in your transformer you are trying to call a method called `SecondaryImages()` on your model, this is a bug in your code, not an issue with Fractal.

**Comment by jbardnz** [comment]
Hey

It could well be an issue with my code but I am not calling SecondaryImages anywhere on my transformer. 

Here is my complete transformer:

    <?php namespace App\Http\Transformers;

    use League\Fractal\TransformerAbstract;
    use App\Models\Listing;


    class ListingTransformer extends TransformerAbstract{


        protected $availableIncludes = [
		'PrimaryImage',
		'SecondaryImages',
		'User'
	];


	public function transform(Listing $listing)
	{
		return [
			'id'            => (int) $listing->id,
			'title'         => $listing->title,
			'url_title'         => $listing->url_title,
			'user_id'         => $listing->user_id,			
			'size'       => $listing->size,
			'size_description'       => $listing->size_description,
			'state'       => $listing->state,			
			'created_at'       => $listing->created_at,
			'updated_at'       => $listing->updated_at
		];
	}

	public function includePrimaryImage(Listing $listing)
	{
		$primaryImage = $listing->primaryImage;

		if($primaryImage){
			return $this->item($primaryImage, new ListingImageTransformer);
		}
		return null;
	}


	public function includeSecondaryImages(Listing $listing)
	{
		$listingImages = $listing->images;

		//filter only secondary images
		$listingImages = $listingImages->filter(function($listingImage){
			return !$listingImage->isMain();
		});

		if(count($listingImages)){
			return $this->collection($listingImages, new ListingImageTransformer);
		}

		return null;

	}
	
	public function includeUser(Listing $listing)
	{
		$user = $listing->user;

		return $this->item($user, new UserTransformer);
	}
}

**Comment by jonlambert** [comment]
Hey @jbardnz, I'm getting this issue too. Did you ever resolve it?

**Comment by jbardnz** [comment]
Hey

No I never did resolve my issue. I would be happy to sent up a fresh Laravel install to test this out if it would help @willishq confirm this is an issue with the package or not?

**Comment by alessione78** [comment]
Hey guys, I'm having the same issue. The strange thing is that on some includes it works, but not on the others. There is no method with same name anywhere.

@willishq can you try to give some more feedback about this issue please?

**Comment by jbardnz** [comment]
Just one thing I discovered while debugging, it seems to only happen when I return a collection. If it just return a single model I never got the error, can anyone confirm the same behaviour?

**Comment by alessione78** [comment]
@jbardnz I just tried and you are right. It happens only when returning collection.

**Comment by alessione78** [comment]
Well, in the end I solve it :) The name of the include should reflect the name of the method that defines the relationship in the model.

So if the include name is includeFoo(Entity $entity) then you should have method "foo()" in the model "Entity"

**Comment by jbardnz** [comment]
Yes you are right, if you only ever use an include name that matches an existing relationship name on your Model then it works.

But as far as I know this isn't how fractal is supposed to work? You as supposed to be able to include any arbitrary data you want with any include name you specify?

**Comment by alessione78** [comment]
I definitely agree with you. But apparently this is working like this now, it would be a good addition if we can just name the includes with arbitrary names.

**Comment by dennisoderwald** [comment]
+1

**Comment by JadoJodo** [comment]
+1
