### ISSUE TITLE
JsonApiSeralizer - Relationships without sideloading

### ISSUE THREAD

**Issue by bobbysciacchitano** [thephpleague/fractal#242]
I'm using Ember with the JsonApiSeralizer and a few of my relationships are loaded async via other API calls and the store. Is it possible to create a relationship reference without having to load the entire object?

**Comment by bobbysciacchitano** [comment]
As a temporary workaround, I've overwritten the item method and just attach the relationship reference to the data array and unset it from the attributes array. Obviously it means relationships becomes a reserved[ish] word and I have to contrive the array by hand but it solves the problem for me.

```
    if (array_key_exists('relationships', $data)) {
        $resource['data']['relationships'] = $data['relationships'];

        unset($resource['data']['attributes']['relationships']);
    }
```

**Comment by willishq** [comment]
I'm going to be looking at the JsonApiSerializer soon to write some documentation for usage and also make sure it's 100% following spec, having looked at the spec there is the scope to add related data without requiring the whole attribute list, I would also like to commend you on the correct use of data caching objects in your application!

**Comment by lukasoppermann** [comment]
@willishq is there any news on this? I am having the same issue, that I need the relationship links, but I do not want to have all the data added.

**Comment by Suven** [comment]
+1

Would really love to see this comming

**Comment by bobbysciacchitano** [comment]
I started my own data serialiser project to overcome this issue ... it's not perfect by any means but ticked the requirements I had at the time. https://github.com/bobbysciacchitano/manuel

**Comment by andersondanilo** [comment]
+1

Really, this is much important
