### ISSUE TITLE
Include params are not optional.

### ISSUE THREAD

**Issue by Perdition** [thephpleague/fractal#250]
The way getIncludeParams() of Manager.php is currently coded means that if no include params are set the function returns nothing instead of returning an "empty" ParamBag instance. The result is that that if an include function in a transformer is expecting a ParamBag argument and no include params are set then an ErrorException is thrown.

This means you are forced to always pass at least one include param or to not have the include function use include params.

**Comment by willishq** [comment]
How are you using the `getIncludeParams` method?

**Comment by Perdition** [comment]
In a Laravel 5 project roughly based on the examples in *Build APIs You Won't Hate*.

If I have something like `includeComments(Book $book, ParamBag $params)` in a transformer and do `GET /books/1?include=comments` I get an ErrorException because Manager.php didn't create a ParamBag to be passed into the function. If I do `GET /books/1?include=comments:order(date)` it works correctly. If I change the `getIncludeParams()` so instead of returning nothing it returns a new ParamBag (whose constructor was passed an empty array) the former GET works fine.

**Comment by alucic** [comment]
I agree that `getIncludeParams` should always return `ParamBag`

@Perdition here's a way around it
```php
    public function includeComments(Book $book, ParamBag $params = null)
    {
        // this guards you from calling function get() on null
    	if ($params != null) {
            list($limit, $offset) = $params->get('limit');  // will return `null` if `limit` is not set
            list($orderCol, $orderBy) = $params->get('order');
        }

        // here you have to guard from calling
        //  `->take(null)`, `->skip(null)`, `orderBy(null, null)`
        $comments = $book->comments;

        if ($limit) {
            $comments = $comments->take($limit);
        }
        ...
        $comments = $comments->get();

        return $this->collection($comments, new CommentTransformer);
    }
```

**Comment by Perdition** [comment]
Thank you very much @alucic. That fixes the issue at least in the case of how I was using it (passing an optional flag to decided whether to use a transformer to include the full data or a transformer to include a succinct version of that data).

**Comment by Chimit** [comment]
Was confused with the same issue. @alucic thank you for advice.
