### ISSUE TITLE
Can I remove the `data` key on included relationships?

### ISSUE THREAD

**Issue by ryanmortier** [thephpleague/fractal#251]
For example, here is my transformer:

```php
<?php

namespace App\Transformers;

use App\Models\AccountFile;
use App\Models\AccountFolder;
use League\Fractal\TransformerAbstract;

class AccountFolderTransformer extends TransformerAbstract
{
    protected $defaultIncludes = ['files'];

    public function transform(AccountFolder $folder)
    {
        return [
            'id'    => e($folder->id),
            'name'  => e($folder->name)
        ];
    }

    public function includeFiles(AccountFolder $folder)
    {
        return $this->collection($folder->files, new AccountFileTransformer());
    }
}

class AccountFileTransformer extends TransformerAbstract
{
    public function transform(AccountFile $file)
    {
        return [
            'id'         => e($file->id),
            'created_at' => e($file->created_at->diffForHumans()),
            'name'       => e($file->name),
            'user'       => e($file->user->name)
        ];
    }
}
```

and here is my current output:

```json
{
    data: [
        {
            id: "1",
            name: "Folder 1",
            files: {
                data: [ ]
            }
        },
        {
            id: "2",
            name: "Folder 2",
            files: {
                data: [
                    {
                        id: "3",
                        created_at: "5 hours ago",
                        name: "File 1.pdf",
                        user: "Ryan Mortier"
                    },
                    {
                        id: "1",
                        created_at: "5 hours ago",
                        name: "File 3.txt",
                        user: "Ryan Mortier"
                    }
                ]
            }
        }
    ]
}
```

As you can see, the nested files has the `data` key when really it should just be an array of files without the `data` key, right? I understand I can remove the `data` key on an `Item`, but not a `Collection`?

**Comment by alucic** [comment]
You can write your own serializer for that.

```php
class YourDataSerializer extends ArraySerializer
{
    public function collection($resourceKey, array $data)
    {
        if ($resourceKey) {
            return [$resourceKey => $data];
        }

        return $data;
    }

    public function item($resourceKey, array $data)
    {
        if ($resourceKey) {
            return [$resourceKey => $data];
        }
        return $data;
    }
}
```

Register your serializer with manager

```php
$manager = new Manager();

$manager->setSerializer(new YourDataSerializer());
```

and when you want to have `data` or anything else you can pass in `resourceKey` to your `Item` or `Collection` as a third param. 

```php
$resource = new Collection($folders, new AccountFolderTransformer(), 'data');
```

**Comment by ryanmortier** [comment]
Ok, thank you!

**Comment by crabbly** [comment]
@alucic Great solution. However, the passed key will be applied to the main object only. Any included resources data will always be added without a key.
Somehow when serializing the includes, the package will use a `null` value for the `$resourceKey`. Which is the default value for the parameter in the `TransformerAbstract` class, `item` and `collect` methods. We can confirm that by running "dump and die" on `$resouceKey` inside the new custom serializer methods.
I will go over the package code and try to figure this out. 
Any help would be appreciated.

**Comment by bikash-s-bhandari** [comment]
i didnt unerstand...where to create the serializer?? and where to write the code
$manager = new Manager();

$manager->setSerializer(new YourDataSerializer());

**Comment by tarcisioruas** [comment]
@bikash-s-bhandari I think you are using Laravel or Lumen to write your program. I think you have a folder named Transformers when you put your data transformer. Why didn't you create a folder named Serializers like you have Transformers folder?
About the code

$manager = new Manager();

$manager->setSerializer(new YourDataSerializer());

The right way is have a BaseController and extends all other controllers from this. If you have a BaseController, you should put that code there.

**Comment by bikash-s-bhandari** [comment]
i still didnt unserstand..i ve a ApiController where i wrote the code
public function news()
    {

        //calling published scope in news model
        $news = News::latest()->published()->paginate(5);
        $newsCollection = $news->getCollection();
        return fractal()
            ->collection($newsCollection)
            ->parseIncludes(['category'])
            ->transformWith(new NewsTransformer)
            ->paginateWith(new IlluminatePaginatorAdapter($news))
            ->toArray();


    }

now i have NewsTransformer which has follwing code
<?php
namespace App\Transformers;

use App\News;


class NewsTransformer extends \League\Fractal\TransformerAbstract
{

    protected $availableIncludes=["category"];
    public function transform(News $news)
    {

        return [
            'id'=>$news->id,
            'title'=>$news->title,
            'sub_title'=>$news->sub_title,
            'author'=>$news->author,
            'content'=>strip_tags($news->content),
            'image'=>asset('public/uploads/news/'.$news->image),
            'publish_at'=>$news->publish_date->format('Y-m-d'),
            'created_at_human'=>$news->created_at->diffForHumans(),


        ];

    }



    public function includeCategory(News $news)
    {

        return $this->item($news->category, new CategoryTransformer);

    }


}


i ve include the category and category transformer is 
<?php
namespace App\Transformers;

use App\Category;


class CategoryTransformer extends \League\Fractal\TransformerAbstract
{

    protected $availableIncludes=["subCategories"];
    public function transform(Category $category)
    {


        return [
            'id'=>$category->id,
            'name'=>$category->name,

            'priority'=>$category->priority,

        ];

    }

    //===========Topic related users and post ni return gareko=============================================

    public function includesubCategories(Category $category)
    {
        return $this->collection($category->subCategories, new SubCatTransformer);

    }


}

now how to remove data key from category?

**Comment by aoxiang594** [comment]
> i didnt unerstand...where to create the serializer?? and where to write the code
> $manager = new Manager();
> 
> $manager->setSerializer(new YourDataSerializer());

https://58hualong.cn/blog/post/ruhe-bimian-transformer-cengceng-de-data-mingming-kongjian

**Comment by Udakara** [comment]
i just write that like this
`return \Response::json([
                'error' => false,
                'data' => $model->toArray()['data'],
                'meta' => $model->toArray()['meta'],
                'status_code' => 200
            ]);`

and it's work's for me

**Comment by rajanand90** [comment]
project name Abcd;

Create Folder -- App\Abcd\Serializers
Create File DataSerializer

<?php
namespace App\Abcd\Serializers;

use League\Fractal\Serializer\ArraySerializer;

class DataSerializer extends ArraySerializer
{

    public function collection($resourceKey, array $data)
    {
        if ($resourceKey) {
            return [$resourceKey => $data];
        }

        return $data;
    }

    public function item($resourceKey, array $data)
    {
        if ($resourceKey) {
            return [$resourceKey => $data];
        }
        return $data;
    }

}


Make one base controller  which extend Controller class and extend by all other Controller
in that controller add this method
<?php

namespace App\Http\Controllers;

use App\Abcd\Serializers\DataSerializer;
use App\Http\Controllers\Controller;
use Dompdf\Dompdf;
use Illuminate\Contracts\Pagination\LengthAwarePaginator;
use Illuminate\Database\Eloquent\Model;
use League\Fractal\Manager;
use League\Fractal\Pagination\IlluminatePaginatorAdapter;
use League\Fractal\Resource\Collection;
use League\Fractal\Resource\Item;

class AppController extends Controller{
   function setResponseData($data, $transformer, $includes = null){
        $resource = null;
        if($data instanceof LengthAwarePaginator){
            $dataCollection = $data->getCollection();
            $resource = new Collection($dataCollection, $transformer, 'data');
            $resource->setPaginator(new IlluminatePaginatorAdapter($data));
        }
        elseif($data instanceof \Illuminate\Database\Eloquent\Collection){
            $resource = new Collection($data, $transformer, 'data');
        }
        elseif($data instanceof Model){
            $resource = new Item($data, $transformer, 'data');
        }
        else{
            return [];
        }

        $manager = new Manager();
        $manager->setSerializer(new DataSerializer());

        if($includes){
            $manager->parseIncludes($includes);
        }

        $content = [];
        if($resource){
            $content = $manager->createData($resource)->toArray();
        }

        return $content;
   }
}

in your controller 
<?php
-- add namespace
use App\User;
class UserController extends AppController{    
     function index(){
        $userList = User::all();
        $transformUsers = $this->setResponseData( $userList, new UserTransformer(), ['profile']);
        return $transformUsers;
     }
}
