### ISSUE TITLE
Potential security/performance issue when using includes

### ISSUE THREAD

**Issue by jonagoldman** [thephpleague/fractal#257]
I discovered this issue using Fractal trough Dingo API and posted the issue there https://github.com/dingo/api/issues/735, but its a general Fractal issue so I reopen it here.

Basically its a side effect of using includes, I am using Laravel's Eloquent but this applies to any type of ORM.

Lets say a user have 1 million posts. I eager load the relationship ```->with(['posts'])```, and constrain it to lets say the latest 30 posts. Then I specify the ```'posts'``` relationship inside the transformer ```$availableIncludes = ['posts']``` in order to tell Fractal to transform that relationship.

But as a side effect, now anyone can add ```'?include=posts'``` to the path and they will get all the posts (no constrains), and I don't have control over it. On the other hand if I don't set the include, then I can't transform the relationship at all...

One solution is ***not*** to lazy load the relationship inside the ```includePosts()``` method, but I want to let API users to do that, but with a default constrain.

**Comment by willishq** [comment]
It's not in Fractal's scope to provide ACL for your resources, if that was the case it would be an API framework. It is up to you to decide who and what gets shown to whom and you can do so in your transformer.

via Eloquent you can pass constraints to the load: https://laravel.com/docs/5.1/eloquent-relationships#eager-loading

Fractal just shows what your application says is allowed to be shown.

**Comment by jonagoldman** [comment]
I'm not talking about permissions. Maybe you should read the issue again, if you want of course.
