### ISSUE TITLE
Could not install fractal package in laravel 5.2 version

### ISSUE THREAD

**Issue by varsadadj** [thephpleague/fractal#266]
I'm trying to install laravel package as per guidance below link:
http://fractal.thephpleague.com/installation/

# <h1>Error

root@tasol-desktop:/var/www/api# composer require league/fractal
Using version ^0.13.0 for league/fractal
./composer.json has been updated
> php artisan clear-compiled
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - ellipsesynergie/api-response 0.9.0 requires league/fractal 0.12.* -> no matching package found.
    - ellipsesynergie/api-response 0.9.0 requires league/fractal 0.12.* -> no matching package found.
    - ellipsesynergie/api-response 0.9.0 requires league/fractal 0.12.* -> no matching package found.
    - Installation request for ellipsesynergie/api-response == 0.9.0.0 -> satisfiable by ellipsesynergie/api-response[0.9.0].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.

**Comment by matthew-james** [comment]
@varsadadj It looks like you are trying to require fractal, but the package you are using (ellipsesynergie/api-response) is already requiring it.

If you want to use fractal by itself you should uninstall ellipsesynergie/api-response first.

**Comment by willishq** [comment]
This is not an issue with Fractal, more an issue with the package `ellipsesynergie/api-response` requiring a different version of Fractal to the one you're trying to require.
