### ISSUE TITLE
Pagination naming

### ISSUE THREAD

**Issue by bobmulder** [thephpleague/fractal#276]
Hi,

I am working on CakePHP 3.x, and tried to create a `PaginatorAdapter` for it.
The documentation and PHPdoc is extremely unclear. For example

```
 /**
    /**
     * Get the count.
     *
     * @return int
     */
    public function getCount()
    {
    }
```
> Count of what?
- All rows in the table (`SELECT * FROM`)?
- Count of the items per page?
- Count of the items of current page?

```
    /**
     * Get the total.
     *
     * @return int
     */
    public function getTotal()
    {
    }
```
> Get the total? 
- All items? 
- Count of all items? (as above?)

```
 /**
     * Get the number per page.
     *
     * @return int
     */
    public function getPerPage()
    {
    }
```
> Get the number of what? 
- The limit? So 10 items per page?

Please make this docs more clear... Or I am stupid and CakePHP does not fit perfectly into the adapter ;)

**Comment by willishq** [comment]
Ok, I guess these could be more clear.

The count is the number of items on the current page.

The total is the total number of items across all pages.

Per page is the maximum number of items per page.

I'll update the docs etc over the weekend!

**Comment by dmitry-varennikov-eventbase** [comment]
Was documentation ever updated? I didn't find it either in the [code](https://github.com/thephpleague/fractal/blob/master/src/Pagination/PaginatorInterface.php) or in [pagination docs](http://fractal.thephpleague.com/pagination/).

```
/**
 * Get the total.
 *
 * @return int
 */
public function getTotal();

/**
 * Get the count.
 *
 * @return int
 */
public function getCount();
```

How good are these comments if they just translate methods' names?

**Comment by lukasoppermann** [comment]
@dmitry-varennikov-eventbase not very good, so why don't you send a PR with improved ones?

**Comment by dmitry-varennikov-eventbase** [comment]
Well I certainly can send a PR with 2 updated comments. But my question was about clarifications on pagination. I see that current issue is closed but apparently no improvements were made. Is it intentional? Help me to understand in order to contribute!

**Comment by davidyell** [comment]
I found this issue for the exact same reasons as @bobmulder it could definitely be clearer
