### ISSUE TITLE
Array serializers don't handle null resource

### ISSUE THREAD

**Issue by golonix** [thephpleague/fractal#278]
In `Scope` class there is method for serializing resource object `serializeResource`:
```
protected function serializeResource(SerializerAbstract $serializer, $data)
{
	$resourceKey = $this->resource->getResourceKey();

	if ($this->resource instanceof Collection) {
		return $serializer->collection($resourceKey, $data);
	}

	if ($this->resource instanceof Item) {
		return $serializer->item($resourceKey, $data);
	}

	return $serializer->null();
}
```
As you can see, if resource is not `Item` nor `Collection`, serialiazer calls `null()` method, which is implemented **only** in `JsonApiSerializer` class.

In order to fix that, I've created PR - https://github.com/thephpleague/fractal/pull/277

**Comment by hiddeco** [comment]
+1 for this

**Comment by willishq** [comment]
This has been merged in now!

**Comment by andrewtweber** [comment]
Why would `null` be serialized as an empty array, and not, you know, `null`?

**Comment by golonix** [comment]
@andrewtweber because it is `array` serializer? Imo, serializer should return always the same type of data.

**Comment by andrewtweber** [comment]
An empty array, from a JSON/JavaScript perspective, seems to imply that it is a collection to me. Which is misleading if that object is usually a single item and not a collection.

Ideally there should be two methods, `$this->nullItem()` and `$this->nullCollection()`

Anyways I can just extend the `ArraySerializer` so I don't feel too strongly about it, I just think it's a flaw of the serializers in general.

**Comment by ImmanuelKannan** [comment]
@andrewtweber Hi Andrew, I hope you don't mind me asking, how would you extend ArraySerializer to return null? I'm at my wits end trying to figure this out. Thank

**Comment by andrewtweber** [comment]
@ImmanuelKannan  sorry for the very late reply but you could simply extend the serializer like this:

```
use League\Fractal\Serializer\ArraySerializer as BaseArraySerializer;

class ArraySerializer extends BaseArraySerializer
{
    public function null() {
        return null;
    }
}
```
