### ISSUE TITLE
Class League\Fractal\Manager does not exist

### ISSUE THREAD

**Issue by yusidabcs** [thephpleague/fractal#28]
Hello, I get this error when try to upload to my vps and run composer, but in local is working. any idea why? thanks

**Comment by yogithesymbian** [comment]
4 month ago, i have solved , but now i dunno why still get message and didnt solve
```
{
  "code": 500,
  "errors": {
    "message": "Target class [League\\Fractal\\Manager] does not exist."
  }
}
```
i have remove vendor folder, `composer self-update && composer dump-autoload` then `composer install`

**Comment by stadskle** [comment]
Did you find an answer to this @yogithesymbian ? The same happened to me when doing composer update and updating from 0.17 to 0.2.1. Looking in the src folder the files are simply missing, does not make any sense...

 
<img width="325" alt="Screenshot 2024-08-04 at 11 12 15" src="https://github.com/user-attachments/assets/8c02fe59-133d-4ebb-ab4d-82ee3f3b2a76">
