### ISSUE TITLE
It's stable, bump to 1.0.0

### ISSUE THREAD

**Issue by Andreyco** [thephpleague/fractal#281]
Since Fractal is stable, consider releasing v1.0.0 to express it's maturity.

**Comment by lukasoppermann** [comment]
I generally agree, but I think there are many issues & PRs that should be fixed / merged before, as the json api specs seem to not be fully supported.

**Comment by willishq** [comment]
I agree with @lukasoppermann, also there's some things which I'm going to merge and refactor before releasing 1.0.0, which will be in the very near future!

**Comment by maximebeaudoin** [comment]
Hello guys ! I'm just wondering if v1.0.0 is going one soon ? I'm wondering because this issue was raised 2 years ago.
