### ISSUE TITLE
Auto-Add links for available includes

### ISSUE THREAD

**Issue by lukasoppermann** [thephpleague/fractal#292]
The way I understand it, default includes & available includes are the relationships an item has, so both should be present as links. Otherwise the user can not know how to get the related data.

@willishq, I don't remember where, but in one issue you said you wanted to work on this, did you get to working on it yet? Is there any way we could help?

I did have a look at the code, but somehow I was not sure where this is actually done. If you can point me in the right direction as to where the default includes are merged and where I would need to add the links from the availableIncludes.

**Comment by bobmulder** [comment]
I also saw that includes are not mentioned in a response. I searche at the JSON API documentation (which is a serializer), but I couldn't find any information about listing the available includes in a response... That's the reason I thought that available includes are never listed in a response....

**Comment by lukasoppermann** [comment]
True it is not mentioned. I filed an issue https://github.com/json-api/json-api/issues/1027 to ask for clarification on this. 

However, fractal offers `links support` on serializers. I think this is a very helpful feature, as it makes sense to always send back relationship links and the payload is minimal. 

> If you want to enable links support, just set a baseUrl on your serializer
http://fractal.thephpleague.com/serializers/#jsonapiserializer

Given this, only including links for resources that are already included makes no sense to me. I would especially be interested in links to resource I have not included, but which are available.

**Comment by bobmulder** [comment]
@lukasoppermann Totally agree!
