### ISSUE TITLE
Exclude defaultIncludes via url

### ISSUE THREAD

**Issue by lukasoppermann** [thephpleague/fractal#307]
When building an api it might make sense to exclude some defaultIncludes on request. 

E.g. you would request `/books?exclude=authors` for listing just the book titles

This is somehow possible using the `parseExcludes` method. However, it is not very convenient, as one can not use the normal transformers in a way it works with includes.

I would love to have an `excludes` parameter just like an `includes` that by default excludes those items from a transformed result.

**Comment by atapatel** [comment]
+1

**Comment by ghprod** [comment]
:+1:

**Comment by jgardezi** [comment]
+1

This would be very help full feature when dealing with roles and permissions.

**Comment by tacony-matt** [comment]
+1

**Comment by FedericoBiccheddu** [comment]
Any update on this?

**Comment by greydnls** [comment]
Happy to accept a PR to add this feature but it's not something that's actively being worked on at the moment.
