### ISSUE TITLE
Release parseExcludes

### ISSUE THREAD

**Issue by lukasoppermann** [thephpleague/fractal#308]
Hey,

for me and some others (e.g. https://github.com/thephpleague/fractal/issues/305) `parseExcludes` is an important feature. However, while it was merged in March it has not been released. 

Could you maybe tag `0.1.14` which would include the `parseExcludes`? I know I can use the `dev` branch, which I currently do, but I am using fractal through dingo, so which could actually use the `parseExcludes` if the release was tagged.

Thanks!

**Comment by bramdevries** [comment]
@willishq possible to release a 0.14.0 version? There's been quite a lot of fixes and new features over the last couple months which we can only use by relying on `dev-master`.

**Comment by willishq** [comment]
@bramdevries I'll release v0.14.0 at the end of this week, I'll have a look over everything and then make sure it's all 100% working first!

**Comment by Mathius17** [comment]
@willishq Is v0.14.0 still coming out? You said you'd release it over a month ago

**Comment by g-van-vreckem** [comment]
I see that v0.14.0 is out.
The changelog.md should be edited to reflect that.
Along with information on;
- parseExcludes
- the annoying backward compatibility breaking change introduced by merge #245:  links are removed from meta pagination and put on the same level as meta.

**Comment by johannesschobel** [comment]
this can be closed as `v.0.15.0` was released today, right?

**Comment by andrewtweber** [comment]
Rather than opening a new issue, figured I would bump this one.

Can we get a new release 0.18.0? It's been over a year since the last one. Thanks in advance!
