### ISSUE TITLE
Exclude *

### ISSUE THREAD

**Issue by lukasoppermann** [thephpleague/fractal#310]
Hey,

I think it would be very helpful if there was a way to exclude everything.

I have the following problem:

I have a potential infinitely nested resource (not really, but I don't know the levels (yet)). 

Pages with includes:
- meta
- tags
- pages (subpages) with includes
  - meta
  - tags
  - pages (...)

Without default includes I would have to send an api request with `includes=pages.meta, pages.tags, pages.pages, pages.pages.meta, pages.pages.tags, pages.pages.pages, ...` this is pretty crazy.

However when displaying a menu I only want to get `pages` and maybe `pages.pages` but certainly no `meta` or `tags`. Manually excluding them would mean the same craziness, just in an exclude statement.

So my hope would be either an includes=pages._,pages.pages._,pages.pages.pages.\* or a similar exclude.

Is there another good or even better solution that I did not notice?

**Comment by greydnls** [comment]
> So my hope would be either an includes=pages.,pages.pages.,pages.pages.pages.* or a similar exclude.

This is a little confusing to me. Can you show a little more clearly what your ideal end solution would look like?

**Comment by lukasoppermann** [comment]
Hey, so basically my problem is the following:

1. given you have a resource that can be related to others of its type e.g. `pages` can have subpages, which are itself a resource of the type `pages`

2. other resources are related to the resources as well, e.g. `pages` might have a `meta` resource relationship, or a relationship to `images` resources

What I want is to get the main resources `pages` without relationships apart from `pages` (subpages), which itself should again have only `pages` (subpages of the subpages).

I hope this makes sense? 😕 

What my idea would be is something like this:

```php
// with defaultIncludes meta, images and pages
api.com/pages/12323442354?exclude=pages.meta,pages.images

// without any defaultIncludes
api.com/pages/12323442354?include=pages
``` 

However this should ALSO effect the included `pages` to only include `pages` and NOT `images` and `meta`.

There might be complications though, when you actually want to include `defaultIncludes` for subpages but maybe you could do:

```php
// without any defaultIncludes
api.com/pages/12323442354?include=pages,pages.pages,pages.meta,pages.images
```

and this would than included the desired items for all following subitems? Or there could be a parameters like `nestedIncludes=true` (which is a very bad name) that would mean that the nested resources of the same type would use the same include rules?

Maybe you have an even better idea?
