### ISSUE TITLE
Is a transformer required to serialize a resource?

### ISSUE THREAD

**Issue by rbellido** [thephpleague/fractal#311]
From the [Simple Example](http://fractal.thephpleague.com/simple-example/) page, we have the following:

```
... (truncated)

$resource = new Collection($books, function(array $book) {
    return [
        'id'      => (int) $book['id'],
        'title'   => $book['title'],
        'year'    => (int) $book['yr'],
        'author'  => [
        	'name'  => $book['author_name'],
        	'email' => $book['author_email'],
        ],
        'links'   => [
            [
                'rel' => 'self',
                'uri' => '/books/'.$book['id'],
            ]
        ]
    ];
});

$array = $fractal->createData($resource)->toArray();
```

which is fine until you pass a `null` in the second parameter in either one of `Collection` or `Item` constructor:

```
$resource = new Collection($books);
$array = $fractal->createData($resource)->toArray();
```

The error I get is as follows:
```
Fatal error: Call to a member function setCurrentScope() on null in /my/app/vendor/league/fractal/src/Scope.php on line 364
```
The constructor in `ResourceAbstract` allows for a `null` transformer so I assumed not passing anything in the 2nd parameter in the constructor is valid. Or should it be that Transformers are mandatory when serializing resources? Any thoughts? And by the way, this is on the latest tag `0.13.0`.

I'd like to determine if this is a known issue, if it is even an issue at all, before submitting a pull request.  Thanks! 😄

**Comment by willishq** [comment]
You need to provide either a `Transformer` or a callback function so Fractal knows how you want to present your data, otherwise, why use Fractal?
