### ISSUE TITLE
Any ETA on a new Tag?

### ISSUE THREAD

**Issue by jaccoTopVintage** [thephpleague/fractal#322]
I noticed that the current master branch is quite some commits ahead of the latest Tag (0.13.0 from 7 Oct 2015).

It would be great is a new version could be tagged as to make the various bugfixes and new features available to the wider audience.

**Comment by ejunker** [comment]
0.14.0 was tagged on 2016-07-21

**Comment by greydnls** [comment]
@ejunker is right! Thanks for pinging me about it, sorry for the dlay.
