### ISSUE TITLE
Transformer recursion issue [all-versions]

### ISSUE THREAD

**Issue by andrewmclagan** [thephpleague/fractal#326]
There exists an issue when transforming entities that have cyclic relationships

For example say we have `organisations` and `user` entities`

`organisations` have users and `users` have an `organisation`

If we have transformers for both these entities that reference each other there exists a infinite loop and accordingly errors are thrown. It seems a very common use-case the have the type of relationships.

Are we missing something obvious?

**Comment by yuloh** [comment]
> If we have transformers for both these entities that reference each other there exists a infinite loop and accordingly errors are thrown

Do you mean reference each other with default includes?  Is this the same issue as #283?

**Comment by andrewmclagan** [comment]
yeah thats it..
