### ISSUE TITLE
Not returning response

### ISSUE THREAD

**Issue by rohitkhatri** [thephpleague/fractal#330]
I'm trying to user resourceKey with transformers, but the response is not coming right. Here's what I have tried:

```
return (new \League\Fractal\Resource\Collection($request->user->friends, new FriendTransformer(), 'friends'));
```

It gives me the following error given below:

```
{
    "message": "The Response content must be a string or object implementing __toString(), \"object\" given.",
    "status_code": 500
}
```

Please help me understand what I'm doing wrong. Thanks

**Comment by yuloh** [comment]
It looks like you are trying to return the resource object directly and your HTTP library is complaining.

Try to transform the resource to JSON before returning it.

```php
$resource = new \League\Fractal\Resource\Collection($request->user->friends, new FriendTransformer(), 'friends');

return $manager->createData($resource)->toJSON();
```

**Comment by rohitkhatri** [comment]
@yuloh Thanks, this worked for me. :-)
