### ISSUE TITLE
Laravel pagination Issuess

### ISSUE THREAD

**Issue by vigneshmuthukrishnan** [thephpleague/fractal#334]
Hi friends i have some problems 
for laravel Pagination
## This is Error

**FatalErrorException in C:\xampp\htdocs\new_laravel\vendor\laravel\framework\src\Illuminate\Foundation\ProviderRepository.php line 146:
Cannot instantiate interface Illuminate\Contracts\Pagination\Paginator**

**Comment by yuloh** [comment]
The laravel paginator doesn't instantiate anything, so this error can't be caused by fractal.  You should just need to call `paginate` on the eloquent query builder to get the `LengthAwarePaginator`.

**Comment by vigneshmuthukrishnan** [comment]
Thank u @yuloh

**Comment by johannesschobel** [comment]
this issue can be closed
