### ISSUE TITLE
Paginator for CodeIgniter

### ISSUE THREAD

**Issue by vinceurag** [thephpleague/fractal#335]
Hi! Please add Paginator for CodeIgniter. or is there a workaround for that as of now? Thanks!

**Comment by yuloh** [comment]
This repo has been pretty inactive so it probably won't be added soon.

If you want to write one you just need to write a class that implements [the PaginatorInterface](https://github.com/thephpleague/fractal/blob/master/src/Pagination/PaginatorInterface.php).

**Comment by willishq** [comment]
Is there much need for an official pagination solution for every framework that people might be using? If that becomes the case, we will end up with a team of people who are just involved in maintaining the paginators!

I think there is actually a case for pulling all the paginators out of the package and putting them into their own smaller repositories which can then be included if you need them, but this will need discussion with @greydnls
