### ISSUE TITLE
Data namespace not removed by serializing collection

### ISSUE THREAD

**Issue by basith374** [thephpleague/fractal#336]
i've a problem. The [ArraySerializer](https://github.com/thephpleague/fractal/blob/0.14.0/src/Serializer/ArraySerializer.php) is not removing data for collections.

[https://github.com/thephpleague/fractal/blob/0.14.0/src/Serializer/ArraySerializer.php#L30](https://github.com/thephpleague/fractal/blob/0.14.0/src/Serializer/ArraySerializer.php#L30)

**Comment by yuloh** [comment]
According to the [documentation](http://fractal.thephpleague.com/serializers/), that is the correct behavior.

> Collections keep the 'data' namespace to avoid confusing JSON when meta data is added.

You can always extend it to not add the `data` namespace.
