### ISSUE TITLE
Allow available and default includes to be defined with a callback

### ISSUE THREAD

**Issue by dwightwatson** [thephpleague/fractal#338]
I have a model that would have different includes available depending on various attributes on it. Because of this it would make sense to be able to change the default available and default includes based upon a model instance rather than hard-coding it on the transformer. 

For example, it could check to see if a method is defined and call that instead of looking up the `$defaultIncludes` property.

```
public function defaultIncludes(Model $model)
{
    return [...];
}
```

Would you be open to this kind of change, or is it not something you'd be interested. Happy to try and put together a PR if it would be considered.

**Comment by catalinux** [comment]
Can't you check on the include method whether you return something or not?


lets say:

```php
function includeSettings(Model $m){
 if($m->specialSettings){
            return $this->item($m->settings, new BaseTransformer());
 }
}

**Comment by dwightwatson** [comment]
Not really, because I have a collection of these models that can all have different available includes. Unless there is another way to go about that?

**Comment by dwightwatson** [comment]
I don't think this is actually an issue, if an includes option doesn't exist then just don't return anything for it. Fractal is smart enough to just omit that from the response, rather than leaving an empty key for it.
