### ISSUE TITLE
Application testing with "includes"

### ISSUE THREAD

**Issue by imjohnbon** [thephpleague/fractal#340]
I'm current using Fractal to build an API in a Laravel 5.3 (latest) environment, but I'm having trouble with my automated application tests. When I run this code:

`$this->json('GET', "api/users/{$user->id}?include=posts");`

It is supposed to give me back a list of users with their posts. When I test the URL in postman or chrome, it works just fine. However when I dump and die the response from the PHPUnit test above, it just includes the users information without the "posts" include.

Does anyone know what's going wrong here? Has anyone successfully gotten Fractal relationships to load when application testing in Laravel?

**Comment by imjohnbon** [comment]
I think I've been able to narrow this down further, it seems like during tests, parseIncludes() doesn't get called on the manager class.

**Comment by imjohnbon** [comment]
Upon further inspection, I'd be willing to bet this is due to the fractal abstraction package I'm using and not fractal itself. Will open an issue with them.

**Comment by imjohnbon** [comment]
I have now tried this with 2 separate abstraction packages:

https://github.com/ellipsesynergie/api-response
https://github.com/spatie/laravel-fractal

And they both have the same issue, which leads me to believe this is either Laravel's issue or Fractals.

**Comment by catalinux** [comment]
What serializer are you using? JsonApiSerializer?

**Comment by imjohnbon** [comment]
@catalinux Correct, I am using this abstraction package (https://github.com/ellipsesynergie/api-response) which defaults to the JsonApiSerializer.

**Comment by imjohnbon** [comment]
Going to close this because the developer of the Fractal abstraction package I am using identified the root cause:

https://github.com/ellipsesynergie/api-response/issues/31

Based on his note, I don't think this is Fractal's issue per-say.
