### ISSUE TITLE
Opinionated library regarding pagination output

### ISSUE THREAD

**Issue by fabiocarneiro** [thephpleague/fractal#341]
I want my pagination data to be part of the root of my collection, somehow what HAL tends to do. (At least for the `_links`) however this library gets key/value https://github.com/thephpleague/fractal/blob/master/src/Scope.php#L269, which either for HAL or a custom implementation might not exist.

**Comment by yuloh** [comment]
I'm pretty sure that method is just setting meta on the resource as key value.

How that looks in the response is up to the serializer.  I'm not really sure how you want the pagination to look in your response but you can take a look at [the JsonApiSerializer](https://github.com/thephpleague/fractal/blob/master/src/Serializer/JsonApiSerializer.php#L99) for an idea of how the serializer serializes the paginator.

Would that work for what you are trying to do?

**Comment by greydnls** [comment]
@fabiocarneiro, @yuloh is correct. Output is up to the serializer. You can implement a custom serializer to output pagination however you like.

**Comment by fabiocarneiro** [comment]
@greydnls No he is not, because the output of serializer is not merged directly in the root, but instead it uses `key()` and `current()` to manipulate the output.

instead of 
```php
$this->resource->setMetaValue(key($pagination), current($pagination));
```
it should be 
```php
$this->resource->setMeta($pagination);
```
