### ISSUE TITLE
Add an abstract method called 'transform' to the `TransformerAbstract`

### ISSUE THREAD

**Issue by leroy0211** [thephpleague/fractal#344]
You should have an abstract method called 'transform' in the `TransformerAbstract` or implement a `TransformerInterface`. Or just add the `transform` method to the TransformerAbstract which just returns the first argument.

Either one of the solutions would suffice.

**Comment by aztech-dev** [comment]
The `transform` method was purposely omitted from `AbstractTransformer` to give implementations the opportunity to type-hint the `transform` parameters, which would otherwise not be possible without using generics.

**Comment by greydnls** [comment]
As was mentioned this is intentionally not included.
