### ISSUE TITLE
Serializing relationships without including data

### ISSUE THREAD

**Issue by willviles** [thephpleague/fractal#346]
Is it possible to serialize a record's relationships data without adding it to the included array?

We're working with an Ember.js frontend with the JSONAPISerializer, which fetches relationships lazily as long as they're represented in the relationships object. Therefore we'd like to implement the pattern detailed in the example below:

```javascript
// api.product.com/foos/1
{
  "data": [
    {
      "type": "foo",
      "id": "1",
      "attributes": {
        "name": "Foo Name"
      },
      "relationships": {
        "bars": {
          "data": {
            "type": "bars",
            "id": "1"
          }
        }
      }
    }
  ]
}

// api.product.com/foos/1?include=bars
{
  "data": [
    {
      "type": "foo",
      "id": "1",
      "attributes": {
        "name": "Foo Name"
      },
      "relationships": {
        "bars": {
          "data": {
            "type": "bars",
            "id": "1"
          }
        }
      }
    }
  ],
  included: [
    {
      "type": "bars",
      "id": "1",
      "attributes": {
        "name": "Bar name",
      }
    }
  ]
}
```

**Comment by catalinux** [comment]
You will have to set `JsonApiSerializer` as a serializer

**Comment by willviles** [comment]
Yeah, @catalinux we're using `JsonApiSerializer`. The issue is there doesn't seem to be a method of serializing the relationship type & id without including the full record in the includes array.

**Comment by catalinux** [comment]
OK. So you would like to skip the `included` key?

**Comment by catalinux** [comment]
I am not sure it works, you have to try:

-  Create a new serialize extending JsonApiSerializer
-  return false for this method:

```php
    /**
     * Indicates if includes should be side-loaded.
     *
     * @return bool
     */
    public function sideloadIncludes()
    {
        return true;
    }

**Comment by willviles** [comment]
Unfortunately that then embeds the relationship data into the attributes hash instead of populating the relationships hash!

```javascript
{
  "data": [
    {
      "type": "foos",
      "id": "1",
      "attributes": {
        "name": "Foo Name",
        "bars": {
          "data": {
            "type": "bars",
            "id": "1",
            "attributes": {
              "name": "Bar Name"
            }
          }
        }
      }
    }
  ]
```

**Comment by morgano86** [comment]
We'd like to include the relationship with a default include (already working)... we don't want this part of the array to appear:

`  included: [
    {
      "type": "bars",
      "id": "1",
      "attributes": {
        "name": "Bar name",
      }
    }`

Unless we strictly ask it to be included with include=<include name>

**Comment by catalinux** [comment]
Can you you paste your transfmer? Is hart to understand what you want to achive

**Comment by catalinux** [comment]
Till now it looks you want
1) to get all the time a `relationship` key for your items.
2) to controll whether you get the sideloaded by using a parameter in your request

**Comment by willviles** [comment]
So, we don't want included records unless we explicitly ask for them:

```javascript
// api.product.com/foos/1?include=bars
included: [
    {
      "type": "bars",
      "id": "1",
      "attributes": {
        "name": "Bar name",
      }
    }
  ]
```

And by default, we want the relationship key set on all requests:

```javascript
"relationships": {
  "bars": {
    "data": {
      "type": "bars",
      "id": "1"
    }
  }
}
```

**Comment by catalinux** [comment]
Ok... you should modify the serializer a little bit. You should not change the current API, so you should leave those alone.

You should use a new parameter like thes sideload=bars,actors and based on the request parameter you should filter the data in the medhod `filterIncludes` from the serializer

**Comment by r-moiseev** [comment]
I wish to iclude relationship `links` object by default. For example if `foo` resource has bars relation, but includes param is empty return this kind of response

```
{
  "data": [
    {
      "type": "foo",
      "id": "1",
      "attributes": {
        "name": "Foo Name"
      },
      "relationships": {
        "bars": {
          "links": {
            "self": "https://my.api/foo/1//bars"
          }
        }
      }
    }
  ]
}
```

**Comment by BastianHofmann** [comment]
@willviles why was this closed? This is clearly missing behaviour, since the JSON:API spec allows for relationships without includes and it have many valid use cases.
