### ISSUE TITLE
Inconsistent types in meta.pagination.links

### ISSUE THREAD

**Issue by appkr** [thephpleague/fractal#348]
When there is data the value is an object:

```json
{
  "data": [
    {...}
  ],
  "meta": {
    "pagination": {
      "total": 20,
      "count": 10,
      "per_page": 10,
      "current_page": 1,
      "total_pages": 2,
      "links": {
        "next": "http://example.com?page=2"
      }
    }
  }
}
```

When there is no data the value is an array:

```json
{
  "data": [],
  "meta": {
    "pagination": {
      "total": 0,
      "count": 0,
      "per_page": 10,
      "current_page": 1,
      "total_pages": 0,
      "links": []
    }
  }
}
```

This makes API client crash, because the response data type was not consistent.

I tried adding if test in `Scope.php:268` and overriding the field value to `null`. But this makes phpunit fail.

```php
if (! empty($pagination)) {
    $value = current($pagination);

    if (empty($value['links'])) {
        $value['links'] = null; // null is OK in API client.
    }

    $this->resource->setMetaValue(key($pagination), $value);
}
```

Any idea?

**EDIT**

I make the phpunit test pass by adding `isset`.

```php
if (isset($value['links']) && empty($value['links'])) {...}
```

**Comment by johannesschobel** [comment]
Is there a PR for this?

**Comment by appkr** [comment]
@johannesschobel Nope for current version though, I made a fork and some modification long time ago, I manually download it during the deployment process[^1]. The modification can be found here. https://github.com/appkr/fractal/blob/fix-pagination-links-data-type/src/Scope.php#L268-L277

[^1]: `wget https://raw.githubusercontent.com/appkr/fractal/fix-pagination-links-data-type/src/Scope.php -O /var/app/current/vendor/league/fractal/src/Scope.php`

**Comment by johannesschobel** [comment]
should we make this an official PR to tackle this issue?!

**Comment by appkr** [comment]
yeah, it would be much appreciated for you to make a PR instead of me. 

2017. 8. 1. 오후 5:22 Johannes Schobel <notifications@github.com> 작성:

**Comment by greydnls** [comment]
Either setting it to null or casting it to an empty object should work, I believe. I'll try to find a moment to address this soon.
