### ISSUE TITLE
Push new Version

### ISSUE THREAD

**Issue by johannesschobel** [thephpleague/fractal#352]
Hey guys,

thanks a lot for your awesome (!) work on fractal. I really like this plugin - awesome functionality.
Do you mind releasing the current state of your work as a 0.14.1 version on packagist? Currently, I am stuck on 0.14.0 (which is dated back to July 2016). However, I need some features merged in August 2016 ( #284 ).

Thanks a lot and happy new year ;)
Johannes

**Comment by johannesschobel** [comment]
Update:
Unfortunately, I am not able to use `dev-master` or something like this, as I use `dingo/api` which requires `league/fractal >= 0.12.0`

**Comment by johannesschobel** [comment]
hey @willishq and others,
can you please give a feedback about the status of this issue? I would *really* appreciate to include this feature in my application..

thanks a lot and cheers

**Comment by amiri27** [comment]
@greydnls any chance to tag a new version?

**Comment by greydnls** [comment]
0.15.0 is released.
