### ISSUE TITLE
Laravel Fractal can't manage includes in Transformer

### ISSUE THREAD

**Issue by gabrielbuzziv** [thephpleague/fractal#356]
## Scenario

I have this 3 Models, Document, Folder and Company.
	- Document belongs to Folder
	- Folder belongs to Comapany and has many Document
	- Company has many Folder

Using fractal i build 3 transformer, one for each model below. And in each transformer i include the relationship, for example `CompanyTransformer` includes folders, the problem is that i can't manage the includes of a included transformer.

So for example, i want to list the documents and show the folders and show the company that the folder belongs, but i can't because is not possible to set include or exclude inside the transformer.

Lets see some code to explain better.

CompanyTransformer.php

```
protected $availableIncludes = ['folders'];

public function transform(Company $company)
{
	return [ 'id' => (int) $company->id ];
}

public function includeFolders(Company $company)
{
	return $this->collection($company->folders, new FolderTransformer());
}
```

FolderTransformer.php

```
protected $availableIncludes = ['company', 'documents'];

public function transform(Folder $folder)
{
	return [ 'id' => (int) $folder->id ];
}

public function includeCompany(Folder $folder)
{
	return $this->item($folder->company, new CompanyTransformer());
}

public function includeDocuments(Folder $folder)
{
	return $this->collection($folder->documents, new DocumentTransformer());
}
```

DocumentTransformer.php

```
protected $availableIncludes = ['folder'];

public function transform(Document $document)
{
	return [ 'id' => (int) $document->id ];
}

public function includeFolder(Document $document)
{
	return $this->item($document->folders, new FolderTransformer());	
	// HERE I SHOULD INCLUDE COMPANY
}
```

In controller if do this, i can't get the folder's company, only the folder.

```

Fractal::create()
	->collection($documents)
	->transformWith(new DocumentTransformer)
	->includeFolders()
	->toArray();

```

**Comment by vidorge** [comment]
try this, if not too late ;)

```
Fractal::create()
	->collection($documents)
	->transformWith(new DocumentTransformer)
	->parseIncludes(['folder.company'])
	->toArray();

```

**Comment by gabrielbuzziv** [comment]
@vidorge hhaa, thanks, i discovery this some days ago :P
