### ISSUE TITLE
Transform on only passed data

### ISSUE THREAD

**Issue by mehranhadidi** [thephpleague/fractal#373]
Hello,

I have an issue on transforming 2 different type of data. 

I have a Transformer for a User array that contains user info.

when i fetch all of the users info and pass it to my transformer it will transform it correctly.

Now i want, when i fetch for example only id & username & pass it to the same transformer  i get an error on undefined array indexes. i dont want to change my transformer to check if that index is exist or create another transformer because its impossible. 

Any solution or fix?

**Comment by Art4** [comment]
Can you provide some code examples please?

**Comment by mehranhadidi** [comment]
@Art4 sure why not.

i have a controller like this that its job to show a user details

```php
public function show(Request $request, $id)
    {
        // Try to find requested user
        $user = User::nFind($id);

        // Throw an error if user not found
        if( ! $user)
            return $this->jsonMessage('User not found.', 404);

        // If user requested for specific user info only return them, nothing more
        if($request->has('only'))
            $user = array_only($user, convert_string_to_array($request->only));

        // Show full user info
        return \Fractal::create()->item($user, new UserTransformer)->toArray();
    }
```

and here is my transformer
```php
public function transform($user)
    {
        return [
            // Basic info
            'id' => $user['id'],
            'name' => $user['name'],
            'email' => $user['email'],
            'username' => $user['username'],

            // Profile
            'birthday' => $user['birthday'],
            'birthplace' => $user['birthplace'],
            'gender' => $user['gender'],
            'description' => $user['description'],

            'created_at' => $user['created_at'],
            'updated_at' => $user['updated_at'],
        ];
    }
```

**Comment by Indemnity83** [comment]
Fractal will let you scope the fields (which happens after the transform), this would probably be the recommended way to handle your situation although it'll have to be a little hacked in because the laravel-fractal library doesn't directly support it yet. 

You could alternatively run your array_only on the return from fractal instead of trying to do it afterward. This is probably the most straight forward way to do this right now. 

```php
public function show(Request $request, $id)
    {
        // Try to find requested user
        $user = User::nFind($id);

        // Throw an error if user not found
        if( ! $user)
            return $this->jsonMessage('User not found.', 404);

        // Transform all the data
        $response = \Fractal::create()->item($user, new UserTransformer)->toArray();

        // If user requested for specific user info only return them, nothing more
        if($request->has('only'))
            $response = array_only($response, convert_string_to_array($request->only));

        // Show full user info
        return $response;
    }
```

**Comment by greydnls** [comment]
What version of PHP are you using? If you're on PHP 7, I would suggest null coalesce operator. Otherwise there's really no way around that.

**Comment by mehranhadidi** [comment]
@Indemnity83 thanks for your reply. actually the problem occur inside of the fractal transformer. because it wants to transform some data that are not passed to it. 

I think this should handle inside of the fractal on transforming level. for example something like this condition: if the variable that you want to transform is set then go for it. 

You solution is outside of the fractal level. 

Any other solution? Thanks

**Comment by mehranhadidi** [comment]
@greydnls I am using php 7.1. Can you describe what do you mean? thanks anyway

**Comment by greydnls** [comment]
```php
public function transform($user)
    {
        return [
            'id' => $user['id'],
            'name' => $user['name'] ?? '',
            'email' => $user['email'] ?? '',
            'username' => $user['username'],
            'birthday' => $user['birthday'] ?? '',
            'birthplace' => $user['birthplace'] ?? '',
            'gender' => $user['gender'] ?? '',
            'description' => $user['description'] ?? '',
            'created_at' => $user['created_at'] ?? '',
            'updated_at' => $user['updated_at'] ?? '',
        ];
    }
```
