### ISSUE TITLE
Issue after update to 0.16

### ISSUE THREAD

**Issue by aistrati** [thephpleague/fractal#374]
Getting an error after upgrading from 0.15 to 0.16:

Type error: Argument 1 passed to League\\Fractal\\Scope::filterFieldsets() must be of the type array, integer given, called in /vendor/league/fractal/src/Scope.php on line 385

**Comment by karlomikus** [comment]
Probably similar issue to #371

**Comment by ejunker** [comment]
I also ran into an error similar to this. I have a transformer that returns an object instead of an array.

**Comment by freekmurze** [comment]
Got this error too. Is there an easy fix for this? You can get the error by running the `it_can_parse_excludes` of the `fractal-0.16` branch of [Fractalistic](https://github.com/spatie/fractalistic)

Same test runs fine on the master branch which uses fractal 0.15

**Comment by greydnls** [comment]
Hi! Sorry for the delay, I'm aware of the issue and should be releasing a bugfix for it very shortly.

**Comment by willemstuursma** [comment]
Thanks, I have the same issue. We have an include that returns `$this->collection(string[])`.

**Comment by AbhijeetSomwanshi** [comment]
I am also having the same Error on updating my Laravel Project with composer update command:


Type error: Argument 1 passed to League\Fractal\Scope::filterFieldsets() must be of the type array, integer given, called in /var/www/html/vendor/league/fractal/src/Scope.php on line 385

**Comment by AbhijeetSomwanshi** [comment]
@greydnls sir, When we will be getting a bugfix for this.

**Comment by willemstuursma** [comment]
I've resolved this with the new 0.17 version using primitives.

My include is now returning `$this->primitive(string[]);` instead of `$this->collection(string[])` which works.

**Comment by davidyell** [comment]
Just ran into this error with an include which returns a collection

**Comment by matthewtrask** [comment]
if this is still an issue, please feel free to reopen, but as we are on 0.20, we are past the version this issue is for.
