### ISSUE TITLE
Transformer in transform method

### ISSUE THREAD

**Issue by Drakota** [thephpleague/fractal#375]
I'm trying to display an item that needs to be treated with an Transfomer. I'm using Laravel 5.4
![image](https://cloud.githubusercontent.com/assets/22665836/25019557/f9d5d346-2058-11e7-8381-8c76e3940b5b.png)
I don't get any error, but it displays nothing. Why?
```
{
  "data": [
    {
      "reservation": {},
      "accepted": 0
    }
  ]
}

```

**Comment by greydnls** [comment]
From your code short I would assume that you would accomplish this with a relationship, rather than using the Item inside the transformer itself. Have you tried that?

**Comment by Drakota** [comment]
I would use relationship, but I don't want to have a data attribute inside it.
Example : 
```
      "invitations": {
        //this "data": [
          {
            "user": {
              "user_id": 1000,
              "first_name": "test",
              "last_name": "test",
              "image_url": "test"
            },
            "accepted": 0
          }
        ]
      }
```

**Comment by greydnls** [comment]
Have you tried calling the transformer directly?

`"reservation" => (new ReservationTransformer)->transform(Reservation::find($....)` ?
