### ISSUE TITLE
Will it support simplePaginate?

### ISSUE THREAD

**Issue by DesmondPang** [thephpleague/fractal#379]
Laravel simplePaginate performs a more efficient query. Will it support simplePaginate?

**Comment by greydnls** [comment]
I'm not intimately familiar with how simplePaginate works. Currently we're using `LengthAwarePaginator`

How would you invision `simplePaginate` being better/different than what's currently being done?

**Comment by DesmondPang** [comment]
From Laravel official page:

> "Simple Pagination"
> 
> If you only need to display simple "Next" and "Previous" links in your pagination view, you may use the simplePaginate method to perform a more efficient query. This is very useful for large datasets when you do not need to display a link for each page number when rendering your view:
`$users = DB::table('users')->simplePaginate(15);`

> 
> $results->count()
> $results->currentPage()
> $results->firstItem()
> $results->hasMorePages()
> $results->lastItem()
> $results->lastPage() (**Not available when using simplePaginate**)
> $results->nextPageUrl()
> $results->perPage()
> $results->previousPageUrl()
> $results->total() (**Not available when using simplePaginate**)
> $results->url($page)

https://laravel.com/docs/5.4/pagination#paginating-query-builder-results

As I said, the simplePaginate has better performance and sometimes we don't need to show the new and previous link in web api. Therefore, simplePaginate is better for building web api. Thanks

**Comment by Art4** [comment]
Looks to me like the cursor principle.
http://fractal.thephpleague.com/pagination/
