### ISSUE TITLE
Use include for fields

### ISSUE THREAD

**Issue by spiroski** [thephpleague/fractal#385]
Is it possible to use include for fields and not relationships?

Let's say i'm requesting user's profile, can I use includes to request additional fields ( like email, age, stuff like that ) and not a relationship?

**Comment by mark-win** [comment]
https://github.com/thephpleague/fractal/pull/389 should do the trick. Hope it gets pulled soon.

**Comment by johannesschobel** [comment]
that would be an awesome contribution!

**Comment by greydnls** [comment]
#389 is merged and should address this issue.
