### ISSUE TITLE
Feature request: PSR-7 standards compliance (and more)

### ISSUE THREAD

**Issue by bingalls** [thephpleague/fractal#393]
You mention plans to comply with http://jsonapi.org/faq/ (compares HAL)
I'm not sure, if various specifications, such as http://json-schema.org/ are compatible.

PSR-7 seems to be gathering consensus in the PHP world.
May I recommend http://swagger.io/open-source-integrations/#php-18
Jane OpenAPI complies with PSR-7, Swagger / Linux OpenAPI (v2) and HTTPlug.
Its PHP source license also looks compatible.

BTW: Sorry, but I'm more likely to join open Mastodon, than Twitter trolls.

**Comment by greydnls** [comment]
PSR-7 is an HTTP Message standard and doesn't really relate to fractal.
