### ISSUE TITLE
Help transforming

### ISSUE THREAD

**Issue by lmarcelocc** [thephpleague/fractal#395]
Hi all,

I'm trying to achive something like this:
`$project = Project::with('projectFiles', 'technologies')->find($projectId); `

 `// Get project files relation and group them by type`
`$files = $project->projectFiles->groupBy('type');`

`// Replace the original with the grouped by project files`
`$project->projectFiles = $files;`
 
Like this, I've something lik (that's what I want):
`projectFiles : {
    screenshots: [],
    project_file: String
}`

But using transformers, how can I achive this?

thank you all!

**Comment by greydnls** [comment]
I'm not familiar with the code that you've got above, but it doesn't look directly fractal related. If you have the code fro your Transformer I'd be happy to try to take a look.

**Comment by lmarcelocc** [comment]
It's solved, thanks :)
