### ISSUE TITLE
Release version with merged code?

### ISSUE THREAD

**Issue by morgandenning** [thephpleague/fractal#399]
We are wanting to use json options in one of our projects, however it looks like https://github.com/thephpleague/fractal/pull/365 has been merged to master, but no new release version has been created.

Due to some dependencies, we are unable to define a `dev-master` version in our composer.json file. Is there a plan for an upcoming release with new merges?

**Comment by balping** [comment]
Same issue here. Please make a release.

**Comment by cviebrock** [comment]
Same here, but I'm hoping to use the Primitive resource type. Thanks!

**Comment by greydnls** [comment]
https://github.com/thephpleague/fractal/releases/tag/0.17.0 Done! Sorry for the delay
