### ISSUE TITLE
[Hateoas] Do you know the Hateoas lib?

### ISSUE THREAD

**Issue by willdurand** [thephpleague/fractal#4]
Hi!

I quickly read your blog post, and saw that you were about to implement Hateoas features into this lib.

Did you consider the [Hateoas](https://github.com/willdurand/Hateoas) library? Or are you aware of it, at least?

Cheers,
William

**Comment by jeboy** [comment]
@philsturgeon how was it? Any support for HATEOAS and is there already a stable version of Fractal for Laravel 5.1?

**Comment by philsturgeon** [comment]
For now, HATEOAS is still achieved via adding `links : []` to your serializer.
