### ISSUE TITLE
Primitive resource bug or question

### ISSUE THREAD

**Issue by terrylow** [thephpleague/fractal#408]
i have the following code to test out the new Primitive resource.

``` php

    $fractal = new Manager();

    // test with string
    //$resource = new \League\Fractal\Resource\Primitive('testing new features 0.17.0');
    
    $resource = new \League\Fractal\Resource\Primitive(['price' => 5 * 100]);

    $array = $fractal->createData($resource);

    return $array->toJson();

```

but i get an InvalidArgumentException
Argument $resource should be an instance of League\Fractal\Resource\Item or League\Fractal\Resource\Collection

Is this a bug or primitive resource is not allowed to use in a base transformer ? If i don't call `toJson()` or any subsequent call after `createData()` then it works

**Comment by atapatel** [comment]
Same issue here.

**Comment by fesor** [comment]
> If i don't call toJson()

Basically if you don't call `toJson` or `toArray` no any resource transformation happens. 

Currently fractal is not allowing to use `Primitive` as resource. It's main purpose is to allow users to expose primitive data without any additional transformation.

**Comment by matthewtrask** [comment]
Im going to close this for now as there wasn't any follow up. Please feel free to reopen.
