### ISSUE TITLE
Serializers part of doc is not up-to-date

### ISSUE THREAD

**Issue by llaville** [thephpleague/fractal#409]
Hello, and big thanks for this great package.

I've used Fractal to build a service following JSON API format, and used the JsonApiSerializer.
All goes fines!

Just a litte error in doc page about Sparse Fieldsets, that tell this feature is not yet implemented. This FALSE !
https://raw.githubusercontent.com/thephpleague/fractal/gh-pages/serializers.md

See the `parseFieldsets()` method of the Manager class

**Comment by llaville** [comment]
**ping** no feedback since a long time

**Comment by KorvinSzanto** [comment]
Hey @llaville, looks like this is still an issue. Do you want to leave this open for now? We are likely to get this resolved soon.
