### ISSUE TITLE
Implement with laravel

### ISSUE THREAD

**Issue by pavinthan** [thephpleague/fractal#410]
Dependency injection not supported TransformerAbstract
I like to create transformers like down blow 

`<?php

namespace App\Transformers;

use App\User;
use League\Fractal\Manager;
use Illuminate\Support\Collection;
use League\Fractal\TransformerAbstract;
use Illuminate\Database\Eloquent\Model;
use League\Fractal\Serializer\DataArraySerializer;
use League\Fractal\Resource\Item as ResourceItem;
use League\Fractal\Resource\Collection as ResourceCollection;

class UserTransformer extends TransformerAbstract
{
    public $manager;

    public function __construct(Manager $manager, DataArraySerializer $serializer)
    {
        $manager->setSerializer($serializer);
        $this->manager = $manager;
    }

    public function transformItem(Model $model)
    {
        $resource = new ResourceItem($model, $this);
        return $this->manager->createData($resource)->toArray();
    }

    public function transformCollection(Collection $models)
    {
        $resource = new ResourceCollection($models, $this);
        return $this->manager->createData($resource)->toArray();
    }
    
    public function transform(User $user)
    {
        return [
            'id' => $user->getAttribute('id'),
            'email'  => $user->getAttribute('email'),
            'created_at'  => $user->getAttribute('created_at')->toDateTimeString(),
            'updated_at'  => $user->getAttribute('updated_at')->toDateTimeString(),
        ];
    }
}`

then I can easily get the data in controller like 

`....
    private $user;
    private $transformer;

    public function __construct(UserRepository $user, UserTransformer $transformer)
    {
        $this->user = $user;
        $this->transformer = $transformer;
    }

    public function index()
    {
        $users = $this->user->index(['roles']);
        $users = $this->transformer->transformCollection($users);
        return $this->user->json($users);
    }
....`

PLEASE SUGGESTS ANY IDEAS IF I WRONG

**Comment by greydnls** [comment]
Can you elaborate? What error are you receiving doing it as you are?

**Comment by pavinthan** [comment]
If I use this way I could not add any includes to the transformation 

`/**
     * Include Roles
     * @param User $user
     * @return \League\Fractal\Resource\Collection
     */
    public function includeRoles(User $user)
    {
        $roles = $user->getRelation('roles');
        return $this->collection($roles, RoleTransformer::class);
    }`

every time I cannot pass require dependencies into `return $this->collection($roles, RoleTransformer::class);` please advice.

**Comment by greydnls** [comment]
The manager and serializer aren't meant to be set on the transformer. Transformers should be very simple data presentation objects. 

That said, if you want to continue doing what you're doing you should be able to pass in `$this->manager` rather than `new Manager()` and have it work as you expect. Again, I don't recommend this.
