### ISSUE TITLE
Includes with actual passed data instead of Item\Collection\Null that implements with ResourceInterface

### ISSUE THREAD

**Issue by daison12006013** [thephpleague/fractal#411]
Most common part of providing a data is to provide the counts for something, counting something really loads a lot or even in DB Query if we want to.

I have these set of counts where I need to count specific statuses for each job, so let us say I have 5statuses, I want to count separate the counting per include.

```
public function includeCountCompleted(Models\Job $job)
{
    return $job->completed()->count();
}
```

The above will never work since it requires us to return a class that implements `ResourceInterface` either [Item, Collection, Null].

In anyway, I could override the `Scope` class to inject something inside `executeResourceTransformers`.

What I could do for now is to include all counters in 1 include as array.

**Comment by terrylow** [comment]
with 0.17.0

you may try the `primitive()`

``` php 

public function includeCountCompleted(Models\Job $job)
{
    return $this->primitive($job->completed()->count());
}

```

and result will then like

``` php 

{
    'id' : '1',
    ....
    'count_completed': '12345'
}

```

**Comment by daison12006013** [comment]
Thanks @terrylow, I didn't notice the `primitive` method.
