### ISSUE TITLE
Laravel pagination with LengthAwarePaginator

### ISSUE THREAD

**Issue by simonschaufi** [thephpleague/fractal#414]
Hello, I was studying the documentation but I still have no glue how to get everything running in Laravel.

What I want is to paginate results that come from an external API (piwik in my case). I need a collection of Objects to put into my view, no simple array or json (like in the docs)!

I have a controller action like this:
```
public function show(PiwikWrapper $piwik, Request $request, Manager $manager, $segment)
{
	$currentCursor = $request->get('cursor', null);
	$previousCursor = $request->get('previous', null);
	$limit = $request->get('limit', 10);

	$offSet = ($currentCursor * $limit) - $limit;

	if ($currentCursor) {
		$lastVisitsDetails = $piwik->getVisitorHistory($segment, $currentCursor, $limit);
	} else {
		$lastVisitsDetails = $piwik->getVisitorHistory($segment, 0, $limit);
	}

	$newCursor = $offSet;
	$cursor = new Cursor($currentCursor, $previousCursor, $newCursor, $lastVisitsDetails->count());

	$resource = new Collection($lastVisitsDetails, new VisitTransformer());
	$resource->setCursor($cursor);

     // not sure what to do from here on...
	$lengthAwarePaginator = new LengthAwarePaginator(
		$lastVisitsDetails->forPage($currentCursor, $limit)->values(),
		count($lastVisitsDetails),
		$limit,
		Paginator::resolveCurrentPage(),
		[
			'path' => $request->url(),
			'query' => $request->query()
		]
	);

	return view('controller.show', [
		'lastVisitsDetails' => $lengthAwarePaginator
	]);
}
```

- Am I doing everything right? I have really no glue if that part of the LengthAwarePaginator is correct.
- How do I get my pagination links now? In standard laravel I would simply to this in my blade template: `{{ $lastVisitsDetails->links() }}` but that doesn't work in this case.

I hope you can help me.

**Comment by greydnls** [comment]
Fractal is for use with APIs only. It doesn't return objects, only formatted data. I don't think this is the tool you should be using.

**Comment by simonschaufi** [comment]
By APIs you mean external APIs or when Laravel serves data with an API to others?
