### ISSUE TITLE
About serializers

### ISSUE THREAD

**Issue by LuCavallin** [thephpleague/fractal#417]
Hi, I am baffled at the first line on this page:

https://fractal.thephpleague.com/

"A Serializer structures your Transformed data in certain ways."

Shouldn't it be the other way around, with transformers applied to serialized data so that you array-once-object can be transformed in structure?

Thank you

**Comment by greydnls** [comment]
I think that's a bit pedantic, but I can understand how it might be confusing. 

Transformers correspond to entities, serializers are more over arching and generally apply to all entities in your application. 

Does that help?

**Comment by LuCavallin** [comment]
Yes, feeling better now.
Thank you for your explanation!
