### ISSUE TITLE
How to add meta fields into included collections?

### ISSUE THREAD

**Issue by chimit** [thephpleague/fractal#419]
I include meta data into transformers using the code like this:
```php
$meta = [
    'count' => (int) $toys->count(),
];

$resource = new Collection($toys, new SomeTransformer, 'items');
$manager = new Manager;
$manager->parseIncludes($request->input('include'));

return array_merge($meta, $manager->setSerializer(new \League\Fractal\Serializer\ArraySerializer())->createData($resource)->toArray());
```
The output is like this:
`GET /children/1/toys`
```
{
    "count": 2,
    "items": [
        {
            "id": 1,
            ...
        },
```
Now I need to include this collection into another request, but I get only the items collection without meta fields:
`GET /children/1?include=toys`
```
{
    "id": 2,
    "child_name": "Bobby",
    "toys": {
        "data": [
            {
                "id": 1,
                ...
            }
        ]
    }
}
```
I need to add `count` field into the `toys` section.

**Comment by matthewtrask** [comment]
Why can you not just add it to the data array for toys?

**Comment by chimit** [comment]
Apparently, I'd been making things too complicated. I simply should use `setMeta` method instead of manually merging arrays.

Anyway thanks for your response, @matthewtrask!
