### ISSUE TITLE
Transformers ignore hidden fields?

### ISSUE THREAD

**Issue by chimit** [thephpleague/fractal#428]
I just noticed that Fractal Transformers ignore model [hidden fields](https://laravel.com/docs/5.5/eloquent-serialization#hiding-attributes-from-json).

**User.php**
```php
class User extends Model implements AuthenticatableContract, AuthorizableContract
{
    use Authenticatable, Authorizable;

    protected $table = 'users';
    protected $hidden = [
        'password',
    ];

    ...
}
```

**UserTransformer.php**
```php
class UserTransformer extends TransformerAbstract
{
    public function transform(User $user)
    {
        return [
            'password' => $user->password,
        ];
    }

    ...
}
```
I still can see the `password` field in the output.

I understand I can simply remove this field from the transformer, but just curious whether it's an intentional behaviour or not.

**Comment by greydnls** [comment]
Is that an eloquent model? The behavior is due to eloquent, not fractal, as far as I know.

**Comment by fesor** [comment]
Hidden attributes are working only for `toArray` method of your model.

https://github.com/illuminate/database/blob/master/Eloquent/Concerns/HasAttributes.php#L289-L291

Nothing can stop you from accessing values of your model via attributes.

**Comment by chimit** [comment]
I still think native Laravel `hidden` feature is good enough to use, so I tried to use it in Fractal transformers in this way:

```php
class User extends Model implements AuthenticatableContract, AuthorizableContract
{
    use Authenticatable, Authorizable, Notifiable;

    protected $hidden = ['password'];

    //...
}
```

```php
class UserTransformer extends Fractal\TransformerAbstract
{
    public function transform(User $user)
    {
        $data = [
            'id' => (int) $user->id,
            'name' => $user->name,
            'password' => $user->password,
        ];

        array_forget($data, $user->getHidden());

        return $data;
    }
}
```
So now we can use Laravel's `makeVisible()` where needed:

```php
// Showing password
$resource = new Fractal\Resource\Item($user->makeVisible('password'), new UserTransformer);

// Not showing password
$resource = new Fractal\Resource\Item($user, new UserTransformer);
```

Any improvement suggestions will be appreciated.
