### ISSUE TITLE
[Question] Why is transform() method not present in TransformerAbstract

### ISSUE THREAD

**Issue by IlCallo** [thephpleague/fractal#429]
The website states

> These classes must extend League\Fractal\TransformerAbstract and contain at the very least a method with the name transform().

for Transformers.

Why isn't it just included as an abstract method on the TransformerAbstract? In that way it would be less error-prone because the IDE (or the compiler) would automatically tell you to implement the method.

Is there something I'm missing?

**Comment by fesor** [comment]
> Is there something I'm missing?

Method signature.

**Comment by IlCallo** [comment]
I see, thank you for the answer
