### ISSUE TITLE
included data serialized with DataArraySerializer, when ArraySerializer is specified

### ISSUE THREAD

**Issue by leroy0211** [thephpleague/fractal#430]
When I want to include some other Transformers, it seems that the included data is serialized with the default `DataArraySerializer` instead of the one I setup (in my case the `ArraySerializer`). 

I have 2 entities, let's say "product" and "category". I want to parse a category, and a category can have multiple products. 

I have setup it like this: 

```php
$manager = new Manager();
$manager->setSerializer(new ArraySerializer());

$category = Category::find(1);
$resource = new Item($category, new CategoryTransformer);

$data = $manager->createData($resource)->toArray();

```

The CategoryTransformer looks like: 

```php
class CategoryTransformer extends TransformerAbstract
{

    protected $availableIncludes = ['products'];
    protected $defaultIncludes = ['products'];

    public function transform(Category $category)
    {
        return [
            'id' => $category->id,
            'name' => $category->name
        ];
    }

    public function includeProducts(Category $category)
    {
        $products = $category->products;
        return $this->collection($products, new ProductTransformer());
    }

}
```

And ProductTransformer just returns the name of a product. 

The result I get for the root object is as expected (without the `data` key), but the `products` key first has a `data` key like this:

```json
{
  "id": "1",
  "name": "Category 1",
  "products": {
    "data": [
      {
        "name": "Article 1"
      },
      {
        "name": "Article 2"
      }
    ]
  }
}

```

The result I would expect is: 

```json
{
  "id": "1",
  "name": "Category 1",
  "products": [
      {
        "name": "Article 1"
      },
      {
        "name": "Article 2"
      }
    ]
}

```

**Comment by IIcuxoIIaTiK** [comment]
Hi, you can create a serializer, in which you can transfer resourceKey = false in order to get rid of the "data" key

Serializer:
```
<?php

namespace App\Serializers;

use League\Fractal\Serializer\ArraySerializer;

class WithoutIncludeDataArraySerializer extends ArraySerializer
{

    public function collection($resourceKey, array $data)
    {
        if($resourceKey === false){
            return $data;
        }
        return [$resourceKey ?: 'data' => $data];
    }

}
```
and use:
`$this->collection($products, new ProductTransformer(), false)`

**Comment by leroy0211** [comment]
Oof, this is a long time ago. Looking at my description I already removed the `$resourceKey` with the `ArraySerializer` but it didn't removed it in the nested included transformers. 
I'm not sure if this is stil happening, because it's been too long. 

I'll close it for now.
