### ISSUE TITLE
use fractal to decode from array to custom PHP object

### ISSUE THREAD

**Issue by montera82** [thephpleague/fractal#431]
using League/fractal, i am attempting to transform data from array to my PHP object...in the following way
```php
    final class StatusDeserializer extends AbstractTransformer
    {
   

       public function transform(Status $status)
       {
          return new StatusObject(
            $status['name'] ,
            $status['message']
          );
       }
    }

    final class StatusObject {

      private $name;
      private $message;
    
      public function __construct($name, $message){
          $this->name    = $name;
          $this->message = $message;
      }
    }

    //test implementation here
    $data = [
        'name' => 'foo',
        'message' => 'bar'
    ]

    $this->fractalManager->createData($data, new StatusDeserializer());
```
But i get this error

    Fatal error: Uncaught TypeError: Argument 1 passed to League\Fractal\Scope::filterFieldsets() must be of the type array, object given

### Edit
I tried wrapping the array into Fractals collection,  i.e

    $data = new Collection([ 'name' => 'foo', 'message' => 'bar' ]);

and it now returns an instance of `League\Fractal\Scope` instead of my StatusObject instance

## Edit 2

Adding ->toArray() brought me back to the first error

    $this->fractalManager->createData($data, new StatusDeserializer())->toArray();

see screen shot : https://gmkr.io/s/5a0b755c683d0d77313ff0fa/0

what i'm i missing ?

**Comment by montera82** [comment]
@willishq ( sorry to mention you directly ) any ideas ?

**Comment by fesor** [comment]
> what i'm i missing ?

transform method should return array (or in case if you use it with `Primitive` resource just any value). So if you need to transform your data into object you may use `Primitive` resource:

```
$this->fractalManager->createData(new Primitive($status), new StatusDeserializer())->toArray();
```

Please note that Fractal isn't serialization/deserialization library. Please use more appropriate solutions like symfony/serializer for this purposes.

**Comment by montera82** [comment]
thanks for your feedback @fesor ,
i tried your suggestion 
`$decoded = $this->fractalManager->createData(new Primitive($status), new StatusDeserializer())->toArray();`

but get this error 

```php
Type: InvalidArgumentException
Message: Argument $resource should be an instance of League\Fractal\Resource\Item or League\Fractal\Resource\Collection
File: /server/http/vendor/league/fractal/src/Scope.php
Line: 355
```

when i remove ->toArray() , and do `var_dump($decoded)` , i get the scope type instead...

```php

object(League\Fractal\Scope)#257 (5) { ["availableIncludes":protected]=> array(0) { } ["scopeIdentifier":protected]=> NULL ["manager":protected]=> object(League\Fractal\Manager)#249 (8) { ["requestedIncludes":protected]=> array(0) { } ["requestedExcludes":protected]=> array(0) { } ["requestedFieldsets":protected]=> array(0) { } ["includeParams":protected]=> array(0) { } ["paramDelimiter":protected]=> string(1) "|" ["recursionLimit":protected]=> int(10) ["serializer":protected]=> object(League\Fractal\Serializer\ArraySerializer)#252 (0) { } ["scopeFactory":"League\Fractal\Manager":private]=> object(League\Fractal\ScopeFactory)#250 (0) { } } ["resource":protected]=> object(League\Fractal\Resource\Primitive)#255 (4) { ["data":protected]=> array(2) { ["service_name"]=> string(5) "joker" ["status"]=> string(4) "cool" } ["meta":protected]=> array(0) { } ["resourceKey":protected]=> NULL ["transformer":protected]=> object(HelloFresh\Purchasing\Infrastructure\Transformer\DeserializerStrategy\HealthStatusDeserializer)#237 (3) { ["availableIncludes":protected]=> array(0) { } ["defaultIncludes":protected]=> array(0) { } ["currentScope":protected]=> NULL } } ["parentScopes":protected]=> array(0) { } }

```

**Comment by greydnls** [comment]
You're attempting to use Fractal in a way that it's not intended, which is causing the issues. Is there a particular reason you're opposed to returning an array from transform? The internals of Fractal rely pretty heavily on that being an array.
