### ISSUE TITLE
How to include plain values?

### ISSUE THREAD

**Issue by chimit** [thephpleague/fractal#432]
The abstract method `item()` in `SerializerAbstract.php` requires the second argument `$data` to be an array. But what if I need to return a plain value as an include? For example, `?include=postsCount`.

The best thing I could do is:
```json
"items": [
{
    "id": 1,
    "name": "John Doe",
    "created_at": "2016-01-14 09:51:12",
    "updated_at": "2016-01-14 09:51:12",
    "posts_count": {
        "count": 79
    }
},
```
My `PostsCountTransformer.php`:
```php
class PostsCountTransformer extends ApiTransformer
{
    public function transform($count)
    {
        return [
            'count' => $count,
        ];
    }
}
```
and I can't simply return `$count`.

What I want to get:
```json
"items": [
{
    "id": 1,
    "name": "John Doe",
    "created_at": "2016-01-14 09:51:12",
    "updated_at": "2016-01-14 09:51:12",
    "posts_count": 79
},
```

**Comment by terrylow** [comment]
you can try primitive resource, under PostTransformer class

```php 

public function includePostCount($resource){
    return $this->primitive($resource->count);
}
```

**Comment by chimit** [comment]
Didn't even know about this method. Had to update my fractal package to get it.
Thank you very much, @terrylow!

**Comment by willishq** [comment]
I'm making a note to add this to the documentation now. @greydnls If you want to do it you can but if you don't / can't I will soon.
