### ISSUE TITLE
Include Model having several relationships

### ISSUE THREAD

**Issue by FabulousCo** [thephpleague/fractal#434]
I'm trying to get a response tree that looks like that:

`

    "data" : {
        "id" : 1,
        "user" : {
            "company" : {
                ... ( data of a company) 
            },
            "followers" : {
                ... (collection of users)
            }
        }
    }

`

I tried this : 
```
    ->createData(new HouseTransformer())
    ->parseIncludes(['user.company', 'user.followers'])
    ->toArray();
```

But it doesn't work...

Any idea how to make this possible using Fractal Transformers ?
  

**UPDATE**

The HouseTransformer looks like that

```
class HouseTransformer extends AbstractTransformer
{
    protected $availableIncludes = [
        'user',
    ];

    public function transform(House $house)
    {
        return [
            'id' => $house->id,
        ];
    }

    public function includeUser(House $house)
    {
        return $this->item($house->user, new UserTransformer());
    }
}
```

and the UserTransformer like that:

```
class UserTransformer extends AbstractTransformer
{
    protected $availableIncludes = [
        'company',
        'followers'
    ];

    public function transform(User $user)
    {
        return [
            'id' => $user->id,
        ];
    }

    public function includeCompany(User $user)
    {
        return $this->item($user->company, new CompanyTransformer());
    }

    public function includeFollowers(User $user)
    {
        return $this->collection($user->followers, new FollowersTransformer());
    }
}
```

**Comment by greydnls** [comment]
I'm assuming that user is a relationship on your house transformer? Can I see that transformer?

**Comment by FabulousCo** [comment]
The HouseTransformer looks like that

class HouseTransformer extends AbstractTransformer
{
    protected $availableIncludes = [
        'user',
    ];

    public function transform(House $house)
    {
        return [
            'id' => $house->id,
        ];
    }

    public function includeUser(House $house)
    {
        return $this->item($house->user, new UserTransformer());
    }
}

**Comment by greydnls** [comment]
Ah, okay, I see now. 

1: Parse includes before `createData()`
2: You need to pass a resource to `createData`, not a transformer. 

Like so: 
```php
$resource = new Fractal\Resource\Item($house, new HouseTransformer());
```

So, in total it would be 

```php
$manager->parseIncludes(['user.company', 'user.followers']);

$resource = new Item($house, new HouseTransformer());

$manager
    ->createData($resource)
    ->toArray();
```

**Comment by FabulousCo** [comment]
It works ! thanks you so much !
