### ISSUE TITLE
Questions about usage of resourceKey in Item

### ISSUE THREAD

**Issue by cberio** [thephpleague/fractal#435]
I've set resourceKey in `Item`, but it never used.

I assume that follwing `Transformer` 

```php
class UserTransformer extends TransformerAbstract
{
    protected $availableIncludes = [ 'userState' ];

    public function transform(User $user)
    {
        return [
            // user attributes
        ];
    }

    pubflic function includeUserState(User $user)
    {
        // User::hasOne(UserState::class)
        $data = $user->userState;

        return $this->item($data, new UserStateTransformer, 'user_state');
    }
}
```

response
```json
{
    "user" :[
        {
            "userState": {}
        }
    ]
}
```
am I doing something wrong or it jsut not implemented yet?

**Comment by greydnls** [comment]
Can you tell me the output you're expecting?

**Comment by cberio** [comment]
`userState` should be `user_state`.
```json
{
    "user" :[
        {
            "user_state": {}
        }
    ]
}
```

**Comment by cryode** [comment]
[Could be a bug with `includeResourceIfAvailable()`, maybe?](https://github.com/thephpleague/fractal/blob/ff99dd5e1b704d83a835d65a1cf812892f9dc9f7/src/TransformerAbstract.php#L160-L162) Doesn't seem to make use of `ResourceAbstract::getResourceKey()` at all, here or on up.

Just a brief run through to try and find the problem, apologies if I missed something and this is inaccurate!

**Comment by cmi90** [comment]
This is my custom serializer

```
namespace App\Serializers;

use League\Fractal\Serializer\ArraySerializer;

class CustomArraySerializer extends ArraySerializer
{
    /**
     * Serialize an item.
     *
     * @param string $resourceKey
     * @param array  $data
     *
     * @return array
     */
    public function item($resourceKey, array $data)
    {
        return $resourceKey ? [$resourceKey => $data] : $data;
    }
}
```

**Comment by johannesschobel** [comment]
from an "easy to consume and extend" point-of-view i would highly encourage you to **not** use the simple `ArraySerializer` but rely on the `DataArraySerializer` or even better to use the `JsonApiSerializer` :heart_eyes:

**Comment by matthewtrask** [comment]
I would agree with @johannesschobel

**Comment by fd6130** [comment]
Still don't know what is the purpose of `$resourceKey` , assign it with string value but it never use.

**Comment by KorvinSzanto** [comment]
@fd6130 The resource key is passed to the serializer during serialization. Whether the resource key is used and how it is used is up to the serializer, you can see how the JSON:API serializer deals with the resource key value [here](https://github.com/thephpleague/fractal-serializer-jsonapi/blob/master/src/JsonApiSerializer.php#L67)
