### ISSUE TITLE
Symfony router with Pagerfanta paginator

### ISSUE THREAD

**Issue by catharsisjelly** [thephpleague/fractal#437]
Hello people,

I'm having a little trouble getting fractal to work with Pagerfanta, Doctrine and Symfony. I have a collection of items and I wanted to get the transformer to work with this. What I am unsure about is what to send the `callable` second parameter to the `PagerfantaPaginatorAdapter`. I could not find any documentation about this and I'm a bit perplexed by it.

I'm happy to write up the docs for it to help contribute to the cause but really unsure of how to do this. `$this->router` is basically an instance of `RouterInterface`

```php
$doctrineAdapter = new DoctrineCollectionAdapter($items);
$paginator = new Pagerfanta($doctrineAdapter);
$adapter = new PagerfantaPaginatorAdapter($paginator, [$this->router, 'generate']);

$resource = new Collection($items, $this->transformer);
$resource->setPaginator($adapter);
return $this->manager->createData($resource);
```

Happy to provide more info if needed.

**Comment by catharsisjelly** [comment]
After a bit of digging and some experimenting, I have got a bit further with this. What I have below here is providing me correct links for the pagination. However, it is always giving me back all of the rows and not 10 as advertised.

```php
$doctrineAdapter = new DoctrineCollectionAdapter($items);
$paginator = new Pagerfanta($doctrineAdapter);
$router = $this->router;
$adapter = new PagerfantaPaginatorAdapter($paginator, function ($page) use ($router) {
    return $router->generate('my_route', ['id' => 1, 'page' => $page]);
});

$resource = new Collection($items, $this->transformer);
$resource->setPaginator($adapter);
return $this->manager->createData($resource);
```

Any help appreciated

**Comment by catharsisjelly** [comment]
Okay, I got it, took me a little while. I might put together a little PR to add this as an example in the documentation. Solution for my problem is below.

```php
$doctrineAdapter = new DoctrineCollectionAdapter($allItems);
$paginator = new Pagerfanta($doctrineAdapter);
$filteredResults = $paginator->getCurrentPageResults();
$router = $this->router;
$paginationAdapter = new PagerfantaPaginatorAdapter($paginator, function ($page) use ($router) {
    return $router->generate('my_route', ['id' => 1, 'page' => $page]);
});

$resource = new Collection($filteredResults, $this->transformer, 'item');
$resource->setPaginator($paginationAdapter);
return $this->manager->createData($resource);
```

**Comment by mnavarrocarter** [comment]
Thanks a lot! Your notes were really useful to me. Maybe I could change a small thing. The way you generate the urls could be improved a little bit passing the request to the callable, like this:

```
$adapter = new PagerfantaPaginatorAdapter($paginator, function($page) use ($request, $router) {
        $route = $request->attributes->get('_route');
        $params = $request->attributes->get('_route_params');
        $newParams = array_merge($params, $request->query->all());
        $newParams['page'] = $page;
        return $router->generate($route, $newParams, 0);
});
```
That way your generated url could support pagination for collections of subresources (/posts/{id}/comments) and also will pass them all the query params used in the previous response, just modifying the page one.

**Comment by catharsisjelly** [comment]
@mnavarrocarter You're very welcome, I'm glad it helped. I have not had a chance to put together a PR as yet. I am concerned that this project may be abandoned since no PR's have been merged since Oct 2017.

**Comment by greydnls** [comment]
Thank you @catharsisjelly, it looks like you were able to get it sorted and helped other people along the way! If you're like to put together a PR for the docs that would be great, but for now it appears this issue is solved. I'm going to close, though feel free to reopen if you disagree.
