### ISSUE TITLE
Fractal, Question about usage for Timezone conversion.

### ISSUE THREAD

**Issue by T0miii** [thephpleague/fractal#441]
Hi,

This is just an overall question, before i decide if i should user Fractal for my problem or not.
Would it be a good practice to convert Date fields btw Timezones in the presenter?
just a simple pseudocode example what i am thinking about:
```
$resource = new Fractal\Resource\Collection($action, function(Book $action) {
    return [
        'appointment_date'      => TimezoneHelper::toTimezone($action->appointment_date, TimezoneHelper::userTimezone());
]
```

**Comment by greydnls** [comment]
Yes, I would consider that appropriate.

**Comment by catalinux** [comment]
One note: API should use time formats that include also timezone. It's up to the client to show in any timezone it wants.

**Comment by T0miii** [comment]
Ok, Thx for the input.
