### ISSUE TITLE
composer install using http

### ISSUE THREAD

**Issue by butlernc** [thephpleague/fractal#442]
composer defaults to only allowing https connections, but your package is located at 
`http://63.236.240.38/UserCheck/PortalMain?IID=27ED9FDF-A92E-0EAC-87F7-EA6FF8423A5A&origUrl=aHR0cDovLzE0NC4yMTcuMjAzLjUzL3AvbGVhZ3VlL2ZyYWN0YWwkODk0ZDM0OWY1NjI2ZDNlNDVlNmIyNmM1NDQ0YTAzZTk0YmRjMDNkODE3OTJiZTM4NjI0MzEzMDZiODlmOTgzNy5qc29u`

when calling `composer require league/fractal`

Could we get this updated so we don't have to turn off secure-http for composer?

**Comment by matthewtrask** [comment]
I dont think we have any control over these types of things, so Im closing this for now.
