### ISSUE TITLE
Nesting recursive structure

### ISSUE THREAD

**Issue by pacoogle** [thephpleague/fractal#444]
Hi to everyone in this repo :-)

Can you help me with the building of this structure?

`{
  "data": [
    {
      "id": "eyJpdiI6IjloNTNwOE9TeGhBY2NCS2hWR2pNM0FRUFVUNGNXaFVPQ2JjRVBDQnJsN009IiwidmFsdWUiOiJFK1hZRUVEZmdEQVEzQlFITEdrRTJQRHBvTmtVUTIwT3d0elgydTUwV3FBPSIsIm1hYyI6ImQwYWEyMTJjYjZiNTJiNWUxMzQ2NjY0Yzc3ZjdhNDJiMTU2OTk3Mzg0MjE4Y2I3Y2VkZTI4YmMyZTYyZTRkNDMifQ==",
      "vanityurl": "pinco_pallino",
      "name": "Pinco Pallino",
      "email": "pinco.pallino@buzzoole.com"
    },
    {
      "id": "eyJpdiI6IlhJTDhNTFwvSWlqNVF6dnRmS2xUZjB3MU9oeGNWK0tyNEltdndYcXN6ZUs0PSIsInZhbHVlIjoicDg3d0IxamY0d1JSTGhsXC95cnNzaUs2d21XY2NqNWhIalwveWp0K21OVVcwPSIsIm1hYyI6Ijk5Y2NmNzI0MWM3NzlmNjMyNjEzZjAwMWVjY2YxNDRiOWQ1YTA4MjAxNDNkZmZkOWZmYzJkNzUyNWIzZDZiYTYifQ==",
      "vanityurl": "pluto",
      "name": "Pluto",
      "email": "pluto@buzzoole.com"
    },
    {
      "id": "eyJpdiI6IlhJTDhNTFwvSWlqNVF6dnRmS2xUZjB3MU9oeGNWK0tyNEltdndYcXN6ZUs0PSIsInZhbHVlIjoicDg3d0IxamY0d1JSTGhsXC95cnNzaUs2d21XY2NqNWhIalwveWp0K21OVVcwPSIsIm1hYyI6Ijk5Y2NmNzI0MWM3NzlmNjMyNjEzZjAwMWVjY2YxNDRiOWQ1YTA4MjAxNDNkZmZkOWZmYzJkNzUyNWIzZDZiYTYifQ==",
      "vanityurl": "Pippo",
      "name": "Pippo",
      "email": "ippo@buzzoole.com"
    }
  ],
  "links": {
    "first": "http://example.com/pagination?page=1",
    "last": "http://example.com/pagination?page=1",
    "prev": null,
    "next": null
  },
  "meta": {
    "current_page": 1,
    "from": 1,
    "last_page": 1,
    "path": "http://example.com/pagination",
    "per_page": 15,
    "to": 15,
    "total": 2
  }
}`

**Comment by johannesschobel** [comment]
I would recommend to take a look at the `DataArraySerializer` or even better the `JsonApiSerializer` for this task. Further, if you try to serialize a `CollectionResource` you can add a `Paginator` which contains the requested pagination information (e.g., current page, next page, ...)
