### ISSUE TITLE
[Feature Request] Custom sort functions for collections to sort by includes

### ISSUE THREAD

**Issue by fschoell** [thephpleague/fractal#450]
Currently it seems that there is no way to sort a resource collection based on includes. See the following example (based on Laravel/Eloquent): 

There is a `Post` model that has many `Comments`. A desirable feature could be to get the post collection sorted by the amount of comments a post received in a certain time. Such a request could look like this:

`GET /api/posts?include=comment_count:since_days(7)&sort=comment_count:desc`

Now, a `PostTransformer` would parse the include parameter and add a primitive for the `comment_count` as requested:

```
class PostTransformer extends TransformerAbstract 
{

  // ...

  public function includeCommentCount(Post $post, ParamBag $params = null) 
  {
    $sinceDays = // ... extract from ParamBag

    $commentCount = $post->getCommentCountAttribute($sinceDays);

    return $this->primitive($commentCount);
  }
}
```

However, the `PostController` that is actually quering the data and adding the transformers doesn't know about that included primitive and hence isn't able to do the sorting itself: 

```
class PostController extends Controller
{
  // ...

  public function index(Request $request)
  {
    $orderCol, $orderBy = // ... parse the sort parameter of the request

    // can't sort by comment_count here, as it is added later by the transformer
    $paginator = Post::orderBy($orderCol, $orderBy)->paginate(20);
    $posts = $paginator->getCollection();

    // can't sort by comment_count here either, as Fractal doesn't allow sorting resources
    return fractal()
      ->collection($posts, new PostTransformer())
      ->parseIncludes(['comment_count'])
      ->paginateWith(new IlluminatePaginatorAdapter($paginator))
      ->toArray();
  }
}
```

Therefore it would be nice to have the possibility to add sort functions. For example something like this:

```
return fractal()
  ->collection($posts, new PostTransformer())
  ->parseIncludes(['comment_count'])
  ->sortWith(function compare($a, $b) {
      return $a->comment_count > $b->comment_count;
  })
  ->paginateWith(new IlluminatePaginatorAdapter($paginator))
  ->toArray();
```

A collection could then utilize PHP's `usort` function to sort the data array using the given compare function (as far as I understood the fractal package). This would allow for more sophisticated sorting abilities, such as sorting a collection based on included primitives (as seen in this example), included items (for example to sort a collection of books by the name of the included author) or even included collections (sort by the size of the included collection for example).

**Comment by greydnls** [comment]
`include` function are for relatioships, not meta or aggregated fields, so I think your usage of that is incorrect. 

Additionally, Fractal doesn't handle any kind of sorting because all of your querying should be done outside of the transformers. I would suggest that you add that comment count to your model, rather than the transformer and do the sorting as part of the query, rather than part of the serialization.

**Comment by osantelices** [comment]
its later I think

you have order and sort when you have the collection
for example

$posts = $paginator->getCollection()->orderBy(anything);
