### ISSUE TITLE
JsonApiSerializer many-to-many pivot data

### ISSUE THREAD

**Issue by Bastinck** [thephpleague/fractal#451]
Cant seem to find a solution to this,

Is this example possible? Where emphasis is pivot data in objective_concepts.

{
  "type": "objective",
  "id": "00559422-02E7-11DB-8468-BA18C3C820AE",
  "relationships": {
    "concepts": {
      "data": [
        { "type": "concept", "id": "02B7", "meta": { "emphasis": "primary" } },
        { "type": "concept", "id": "3AF6", "meta": { "emphasis": "secondary" } },
        { "type": "concept", "id": "CB23", "meta": { "emphasis": "tertiary" } }
      ]
    }
  }
}

**Comment by greydnls** [comment]
I don't believe meta on relationships is currently supported, but I'd need to look into it. If it's not, I'd be happy to see a pull request to support it.

**Comment by Bastinck** [comment]
Thanks for your quick reply!

However, this test shows a many to one relation, How would you add the meta if a book has multiple authors?

**Comment by J5Dev** [comment]
Hi did you resolve this... I know I'm late, but I have hit the same wall and haven't got round to a neat solution...
