### ISSUE TITLE
Why it's not possible to add custom links if baseUrl is not defined ?

### ISSUE THREAD

**Issue by shulard** [thephpleague/fractal#456]
Hello,

I'm currently using Fractal on an API project and I faced a little issue/question regarding the JsonApiSerializer.

It seems that to use the links, it's mandatory to set the `baseUrl` parameter. But what if I only want to add custom links but not the auto generated one ?

Actually, if I define a custom `self` link, it's never used because it's overwritten by the auto generated one. I needed to extend the JsonApiSerializer to customize a little it's behaviour.

Is it a normal behaviour ? Have I misunderstood something ?

**Comment by matthewtrask** [comment]
this is a few years old so Im going to close it for now. If it is still an issue please feel free to reopen or create a new issue.
