### ISSUE TITLE
Data containing only strings.

### ISSUE THREAD

**Issue by rsukonovs** [thephpleague/fractal#466]
I am refactoring existing API and i need to return response ``{"data":["one","two"]}``. Is this possible in version 0.17? I have played around and 0.15 seems to be able construct such json as in example:
```
$resource = new Collection($books, function(string $string) {
    return $string;
});

echo $fractal->createData($resource)->toJson();
```

But in version 0.17 this is broken. I am aware of Primitive object, but it seems to be working only work if `"data"` has items which are arrays not just strings.

**Comment by matthewtrask** [comment]
Im going to see if I can recreate this some time this week.

**Comment by KorvinSzanto** [comment]
At this point the only way to get around this would be to use a custom `ScopeFactory` and return an instance that extends the `Scope` we have today and implements the change from #473. Beyond that you'd need to wait until the next release.

**Comment by KorvinSzanto** [comment]
I was a little quick to reply, my solution isn't a great fit for what we have today.

At this point transformer methods must return an `array` even if your data is a scalar value. 
Try changing your return to something like `['string' => $string]` then you can implement a serializer that outputs your data how you'd like.
