### ISSUE TITLE
Drop support for PHP 5 and set new minimum to 7.2

### ISSUE THREAD

**Issue by KorvinSzanto** [thephpleague/fractal#471]
Our current minimum PHP version is `5.4`, this has the following effects:

- Automated testing in CI slow and requires 7 separate environments to test all versions
- We contribute to an ecosystem of packages based on versions of PHP that are unsupported and potentially insecure
- We limit ourselves to old language functionality and can't make use of better patterns like type hinting

I propose we up the minimum PHP requirement for `0.18.0` to PHP `7.2` and update all implementations and interfaces to make use of scalar type hinting and return types.

Related Work:

- [x] 6e5e107 Update to PHP 7.2 minimum with working tests
- [ ] Update documentation to reflect this update

**Comment by KorvinSzanto** [comment]
Let's do this for `1.0.0` instead of `0.18.0`. We'd like to leave `0.x` as backwards compatible as possible.

**Comment by KorvinSzanto** [comment]
#476 is the beginnings of this

**Comment by fenric** [comment]
How is it going? Is this project still supported?

**Comment by Nyholm** [comment]
This is fixed in master.
