### ISSUE TITLE
.NET Equivalent?

### ISSUE THREAD

**Issue by mattkoch614** [thephpleague/fractal#478]
Hi @philsturgeon - Any idea if something similar to Fractal exists for ASP.NET Core? I've used this package with PHP before and really like it, but cannot find anything equivalent in the .NET space. I wasn't sure where else to post this, so feel free to close if it's better suited elsewhere.

**Comment by matthewtrask** [comment]
@mattkoch614 just asked in the "apis you wont hate" channel to see. If there is, I will post it here for you.

**Comment by matthewtrask** [comment]
@mattkoch614 based on a cursory search, it seems like there is enough in the SPL of .NET/C# to get you what you need without an external package. Im not a C# developer but I can try to help you if you need it.

**Comment by mattkoch614** [comment]
Thanks @matthewtrask, we can close this issue.
