### ISSUE TITLE
Pull out paginators

### ISSUE THREAD

**Issue by matthewtrask** [thephpleague/fractal#480]
Fractal ships with the following paginators:

* Doctrine
* Phlacon
* Laravel
* PagerFanta
* Zend

I think we should make a basic paginator class, and move these 5 to separate repositories that can be suggested via Composer. 

Thoughts?

**Comment by johannesschobel** [comment]
In general, i think, this is a good idea.. However, this would make the release-process of a new fractal version way more complicated, because you need to keep those packages in-sync..

**Comment by matthewtrask** [comment]
@johannesschobel I agree. But since the paginators (probably) won't change much, it might not be terrible to maintain them. Or even find people who are willing to help us keep up.

**Comment by johannesschobel** [comment]
I definitely agree, that it would add a certain level of flexibility.. 
All the best

**Comment by KorvinSzanto** [comment]
I agree these are best separated out, this was brought up as part of #474. 

> this would make the release-process of a new fractal version way more complicated, because you need to keep those packages in-sync

One thing to remember with releases is that we don't necessarily have to release a new version of the paginators / serializers every time we release a core version. There are option, for example we might want to keep just the major version numbers in sync.

**Comment by KorvinSzanto** [comment]
I've split out the paginators:
- Doctrine pagination: https://github.com/thephpleague/fractal-paginator-doctrine
- Illuminate pagination: https://github.com/thephpleague/fractal-paginator-illuminate
- Pagerfanta pagination: https://github.com/thephpleague/fractal-paginator-pagerfanta
- Phalcon pagination: https://github.com/thephpleague/fractal-paginator-phalcon
- Zend pagination: https://github.com/thephpleague/fractal-paginator-zend

Just need to get an array paginator and an iterator paginator setup and we should be good.

**Comment by matthewtrask** [comment]
Im going to close this for now.
