### ISSUE TITLE
Hydra support

### ISSUE THREAD

**Issue by AzeemMichael** [thephpleague/fractal#483]
Any chance we can have Hydra support http://www.hydra-cg.com

**Comment by matthewtrask** [comment]
this is the first I have heard of Hydra. I am reading the spec and trying to wrap my head around it. Can you give me some of the details about what you like about it, or what problems it solves that a data array or JSON:API does not?

**Comment by matthewtrask** [comment]
Im going to close this for now, if this is still an issue please reopen or create a new issue. thanks!
