### ISSUE TITLE
Move to Github Actions

### ISSUE THREAD

**Issue by matthewtrask** [thephpleague/fractal#501]
Now that Github Actions are gaining wide usage, we should drop Travis and Circle and solely use Github actions. Less service integration to maintain.

**Comment by KorvinSzanto** [comment]
I'd love to see this working, we might be able to get the change back into https://github.com/thephpleague/skeleton if we can make it generic :+1: :+1:

**Comment by JustSteveKing** [comment]
@matthewtrask want me to handle this one?

**Comment by matthewtrask** [comment]
@JustSteveKing that would be great!

**Comment by KorvinSzanto** [comment]
Thanks @JustSteveKing, next steps on this are:
1. Move the adapter / paginator repos over to github actions as well
2. Update this repo to only test 5.6+

**Comment by JustSteveKing** [comment]
No problem @KorvinSzanto if I'm honest I'd be tempted to raise the min PHP version to the officially supported one.

I'm happy to look at the pagination adapters repo if needed, just give me a shout!
