### ISSUE TITLE
Return array when attributes aren't provided instead of object

### ISSUE THREAD

**Issue by sangar82** [thephpleague/fractal#504]
Hi!

After upgrade to version 0.19 and upgrade my app, my customers had breaking changes caused by changes made on 0.18 because they are waiting for an array when the attribute is empty:

> Output an object for attributes when none are provided instead of an array in JsonApiSerializer - Thanks @BastianHofmann
https://github.com/thephpleague/fractal/releases/tag/0.18.0

Is there a way to mantain the same behaviour under 0.18? I need to show an empty array in this cases.

I've been forced to downgrade to 0.17.

Thanks for your job!

**Comment by BastianHofmann** [comment]
The JsonApiSerializer adheres to the JSON:API specification, which states that attributes **must** be an object (https://jsonapi.org/format/#document-resource-object-attributes).
Your options are downgrading or fixing the client implementation.

**Comment by sangar82** [comment]
Ok! thanks for your fast reply
