### ISSUE TITLE
How to remove the 'self' link from a relationship links object when using the JsonApiSerializer

### ISSUE THREAD

**Issue by J5Dev** [thephpleague/fractal#518]
As the title says, I seem to be at an impasse with regards to how to (or if you can at all) remove the "self" link from the relationships object.

As per the V1.0 specification... https://jsonapi.org/format/#document-resource-object-relationships

> A  “relationship object” MUST contain at least one of the following:
> 
> links: a links object containing at least one of the following:
> self: a link for the relationship itself (a “relationship link”). This link allows the client to directly manipulate the relationship. For example, removing an author through an article’s relationship URL would disconnect the person from the article without deleting the people resource itself. When fetched successfully, this link returns the linkage for the related resources as its primary data. (See Fetching Relationships.)
> related: a related resource link

We are implementing out API whereby we do not want the relationship to be manipulated directly, and as such, do not want the "self" link declaring.

Our issue therefore is not with the spec itself, as we will be including the related link, and as such will be compliant. The issue is the ability to override what looks like a hard-coded set of links, as per the below.

JsonApiSerializer.php
```php
$resource['relationships'][$relationshipKey] = array_merge(
    [
        'links' => [
            'self' => "{$this->baseUrl}/{$resource['type']}/{$resource['id']}/relationships/{$relationshipKey}",
            'related' => "{$this->baseUrl}/{$resource['type']}/{$resource['id']}/{$relationshipKey}",
        ]
    ],
    $resource['relationships'][$relationshipKey]
);
```

I have searched the issues as best I can related to how to remove the link, as well as trawled through the serializer, however cannot find a way to remove/suppress the "self" link (other than creating a fully custom serializer that is).

Am I going mad, or is this not available?

Happy to work on a solution if it isn't available, just figured I would ask before getting stuck i.

**Comment by JoeAlamo** [comment]
you need to extend the serializer and override injectAvailableIncludeData method to call a new addRelationshipLinks method.

**Comment by J5Dev** [comment]
Hi Joe,

Yep, knew that was a possibility, just wanted to sound out the community before doing so... nothing worse than doubling up.

Thanks for your answer :)
