### ISSUE TITLE
Modernize like it's 1.0

### ISSUE THREAD

**Issue by matthewtrask** [thephpleague/fractal#525]
ok so this project has kind of been. It was stable, but not without its issues. But in that time PHP has grown up quite a bit and its time this library gets with the times. This will ultimately result in a 1.0 tag (yay) but it may be painful for the people using 0.19 (or the current version). 

**While we can't make any promises, we will try to make it as painless as we can**

Things on the list:

- [ ] php 7.3 minimum (8.0 is the goal, but I know not every app/project is on 8.0)
- [ ] static analysis (psalm and phpstan)
- [ ] null object support
- [ ] empty object support
- [ ] clean up codebase
- [ ] update json api serializer
- [ ] drop travis support (we use github actions now)
- [x] add test coverage to the paginators

at one point, we considered moving the serializers out to their own packages, but I fear that would be too much work and easy for a package to fall in disrepair.

**Comment by matthewtrask** [comment]
>add test coverage to the paginators

updating Mockery fixed this.

**Comment by cebe** [comment]
@matthewtrask why did you close this? Did the plans change? If so, how? :)
