### ISSUE TITLE
What a current state of this project? PHP8 support plans? 

### ISSUE THREAD

**Issue by Insolita** [thephpleague/fractal#526]
The last commit was made more than a year ago. What is the project's future plans?

**Comment by annuh** [comment]
The latest release candidate (PHP 8.1 RC6) gives the following error:

```
Fatal error: During inheritance of JsonSerializable: Uncaught ErrorException: Return type of League\Fractal\Scope::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in vendor/league/fractal/src/Scope.php:298
```

Created a small fix for this: https://github.com/thephpleague/fractal/compare/master...annuh:support-php-8-1

composer.json
```json
{
    "repositories": [
        {
            "url": "https://github.com/annuh/fractal.git",
            "type": "vcs"
        }
    ],
    "require": {
        "league/fractal": "dev-support-php-8-1#f4f97897d351bbfd626dc1143a962395b0352d6b"
    }
}
```

**Comment by patrick-radius** [comment]
Please please don't let us hanging here

**Comment by matthewtrask** [comment]
@patrick-radius @annuh @Insolita we are back, after life getting in the way and are currently working towards a 1.x with php 8 support. If there are specific things you want us to consider feature wise, please open a new issue with the request.
