### ISSUE TITLE
Support for returning a subset of fields on a resource

### ISSUE THREAD

**Issue by benglass** [thephpleague/fractal#54]
Perhaps this feature already exists but I am thinking it would be nice to have a recommended way of returning a subset of data for a resource via a transformer.

This can obviously be achieved by providing a separate transformer or implementing this logic in your own transformer but I am wondering if it would be a beneficial feature to add to the abstract transformer.

Basic idea would be something like this:

https://gist.github.com/benglass/e7b2af60451d2a46182b

It would also be nice to be able to cascade the group name to embedded transformers

Use cases for this would be
* Public vs Private APIs
* Versioning for APIs

Obviously this could be achieved by just defining separate transformers but then you would have to duplicate some of the field extraction logic. You could mitigate this by creating a field extractor that is used by the transformers but since that is the main thing the transformers do it seems like that would be overengineering.

**Comment by jsdecena** [comment]
Any final decision on this or a PR was made since 4y ago?

**Comment by siarheipashkevich** [comment]
Any news?

**Comment by philsturgeon** [comment]
This issue was closed in 2015 and the last comment said the issue was resolved in https://github.com/thephpleague/fractal/issues/226. What other news were you looking for?
