### ISSUE TITLE
How to create custom ArraySerializer with the result of meta pagination array inside the collection array

### ISSUE THREAD

**Issue by suariana** [thephpleague/fractal#550]
hello, im trying to make a custom Array Serializer the code is like this :

![image](https://user-images.githubusercontent.com/47437771/158001959-7bd91738-f115-4d7c-9c8c-fbf0e47c2b0d.png)

the result is like this : 
![image](https://user-images.githubusercontent.com/47437771/158002363-06c86cdb-26bc-4431-b186-d0fb143d9961.png)

but the result that i want to return is like this : 
![image](https://user-images.githubusercontent.com/47437771/158002501-da9f7a3d-5c5a-4d03-868f-111148f49b3c.png)

Is there anyone who can help find a solution?
thanks..

**Comment by matthewtrask** [comment]
@suariana did you find the solution or did you close by accident?

**Comment by suariana** [comment]
yes, i found the solution by modify the result on meta function..
