### ISSUE TITLE
Found 2 security vulnerability advisories affecting 2 packages.

### ISSUE THREAD

**Issue by Malith1994124** [thephpleague/fractal#571]
![image](https://github.com/user-attachments/assets/fc8fdddd-876e-48bd-8a9f-d48b6477bcf8)

Got 2 security vulnerabilities while installing version 0.20.1.

**Comment by jdreesen** [comment]
They have nothing to do with this package. Just update your Symfony dependencies and you're fine.

**Comment by KorvinSzanto** [comment]
Fractal doesn't currently have any dependencies other than PHP, you can use `composer why ...` to see why these packages are being included in your project.
