### ISSUE TITLE
Transforming incoming data?

### ISSUE THREAD

**Issue by tpavlek** [thephpleague/fractal#65]
Forgive me if I'm missing something, but it's not immediately apparent to me nor does it seem to be mentioned in the docs:

What about recieving data? If I have an object in the database, and for simplicity's sake let's us the example that in the database a column is called "start_date", I transform this to simply be "start" when it's sent to the client. Now, when I recieve data back, it will obviously just be a "start" property, which isn't actually in the database.

Do transformers support inverting their own operations?

**Comment by GPHemsley** [comment]
@philsturgeon That link is now dead, and in any case refers to Ruby code, not PHP code. Do you have any recommendations for getting this behavior in a way that complements a Fractal transformer? Is there any likelihood in it being added here? (I note that this issue and many similar ones remain closed.)
