### ISSUE TITLE
Avoid `data` in included elements?

### ISSUE THREAD

**Issue by lowerends** [thephpleague/fractal#90]
Is there a way to **not** have the `data` key as part of the included elements, while still keeping it for the top level response data?

**Comment by boukeversteegh** [comment]
Based on @mediaholding I am using the following solution. Notice that by default, when ``$resourceKey === null`` the serializer will create ``data``, as per original implementation.

```php
/**
 * Create a new Serializer in your project
 */
use League\Fractal\Serializer\ArraySerializer;

class DataArraySerializer extends ArraySerializer
{
    public function collection($resourceKey, array $data)
    {
        return $resourceKey === false ? $data : array('data' => $data);
    }

    public function item($resourceKey, array $data)
    {
        return $resourceKey === false ? $data : array('data' => $data);
    }
}
```

```php
# Set the serializer on fractal manager
$manager = new League\Fractal\Manager();
$manager->setSerializer(new DataArraySerializer());

# Or if you are using the ellipsesynergie/api-response package for Laravel
$this->response->getManager()->setSerializer(new DataArraySerializer());
```

It is fully backwards compatible, except that if you pass ``false`` as a resource key, it does not generate a ``{"data": .... }`` wrapper.

For example, I have this transformer:

```php
class FriendshipTransformer extends TransformerAbstract
{
    protected $availableIncludes = [
        'user',
    ];

    public function transform(Friendship $friendship)
    {
        return $friendship->toArray();
    }

    public function includeUser(Friendship $friendship)
    {
        // pass false as resourceKey
        return $this->item($friendship->user, new UserTransformer, false);
    }
}
```

**Comment by ddctd143** [comment]
@boukeversteegh Your implementation does not allow to use custom data key, because in your overriding methods $resourceKey isn't used at all.

At example, if you need to specify data key, but you need to use a custom key, then this implementation should work

```
    public function collection($resourceKey, array $data)
    {
        return $resourceKey === false ? $data : [$resourceKey => $data];
    }

    public function item($resourceKey, array $data)
    {
        return $resourceKey === false ? $data : [$resourceKey => $data];
    }
```

**Comment by boukeversteegh** [comment]
oh you are right, that was a pretty bad mistake. let me correct. i would like this behavior:

false results in no wrapper array at all
null results in 'data'
anything else results in anything else

let me rewrite

**Comment by boukeversteegh** [comment]
I am working on a PR to implement optional, yet customizable resource keys (wrapper arrays) but I'm having trouble understanding the intention behind DataArraySerializer and ArraySerializer. Hopefully @localheinz or @philsturgeon can help out.

From the unit tests, it seems that DataArraySerializer is ignoring the resourceKey on purpose. I.e: even though the transformer sets the resourceKey to "author", the array is returned as ``{"author": {"data": {"name": "Dave"}}}``. If I add support for overriding the ``data`` key with the resourceKey, the unit tests break, and it would break backwards compatibility with codebases that use resourceKeys, but expect them to be ignored.

Otherwise I could add this feature to ArraySerializer, but that one does not wrap items. In my opinion neither serializers make much sense. The ArraySerializer uses the resourceKey only for collections, and does not allow disabling. The DataSerializer also wraps single items, but does not allow overriding, nor disabling the data key.

IMO all of this functionality could and should be supported by a single Serializer such as the one I proposed above. 

Now the question is should we support this flexibility by breaking compatibility, or by adding a new serializer, and if so what should it be called.

``ResourceArraySerializer``
``NamedArraySerializer``
``FlexArraySerializer``
``DefaultArraySerializer``
``ResourceKeyArraySerializer``

What do you think? I will PR soon if we can come up with a nice solution.

**Comment by aleemb** [comment]
@boukeversteegh Maybe have a it called PlainOldSerializer in spirit of the POJO/POCO convention and matching user expectations.

**Comment by aftabnaveed** [comment]
@boukeversteegh did you create a PR for that already, and has it been merged?

**Comment by ryanrca** [comment]
New to fractal, and ran into this today.  Our data structures nest a lot of includes.  My front end dev is not happy with having to write object keys like this:
```
var genres = music.data.productable.data.decorators.data.genres;
```
It gets pretty long winded.  
We would be a lot happier if it were more concise:
```
var genres = music.data.productable.decorators.genres;
```

Status of this PR?

**Comment by philsturgeon** [comment]
One idea is to write an abstraction layer instead of trying to make the API output data in exactly the right structure for the front end developer?

Generally different front end developers want different things, so you can't please them all.

**Comment by michaeldnelson** [comment]
I will +1 this I will also be writing a custom serializer to make my api more readable.  Is nesting object attributes in a data property a standard I should be aware of or is this just a quirk of the library?

**Comment by philsturgeon** [comment]
It’s incredibly common to use an envelope yes, which isn’t ideal but is required to add metadata to a collection as this library does. 

--
Phil Sturgeon
@philsturgeon

**Comment by cristenicu** [comment]
To wrap the response with `data` I used an `ArraySerializer` and Dingo's morphed event
```php
protected $listen = [
    'Dingo\Api\Event\ResponseWasMorphed' => [
    	'App\Listeners\FormatDingoResponse'
    ]
];
```
```php
class FormatDingoResponse
{
    public function handle(\Dingo\Api\Event\ResponseWasMorphed $event)
    {
        $data = isset($event->content['data']) ? $event->content['data'] : $event->content;
        unset($data['meta']);

        $meta = isset($event->content['meta']) ? $event->content['meta'] : [];

        $event->content = ['data' => $data, 'meta' => $meta];
    }
}
```

**Comment by youmax210139** [comment]
better to overwrite the serializer within dingo

```php
class AppServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        if ($adapter = app('api.transformer')->getAdapter()) {
            $manager = $adapter->getFractal();
            $manager->setSerializer(new \App\Transformers\Serializer\DataArraySerializer());
        }
    }
}
```

**Comment by mrFANRA** [comment]
> Based on @mediaholding I am using the following solution. Notice that by default, when `$resourceKey === null` the serializer will create `data`, as per original implementation.
> 

PHP8  changed types support, now it is not working, In new version need add false var type in function. Temporary make like this =(

```
class MyArraySerializer extends ArraySerializer
{
    const NOWRAP = 'nowrap';

    public function collection($resourceKey, array $data): array
    {
        if ($resourceKey == self::NOWRAP) {
            return $data;
        }
        return array($resourceKey ?: 'data' => $data);
    }

    public function item($resourceKey, array $data): array
    {

        if ($resourceKey == self::NOWRAP) {
            return $data;
        }
        return array($resourceKey ?: 'data' => $data);
    }
}
```



Usage:


```
class FriendshipTransformer extends TransformerAbstract
{
    protected $availableIncludes = [
        'user',
    ];

    public function transform(Friendship $friendship)
    {
        return $friendship->toArray();
    }

    public function includeUser(Friendship $friendship)
    {
        // pass false as resourceKey
        return $this->item($friendship->user, new UserTransformer, MyArraySerializer::NOWRAP);
    }
}
```
